And 1784 add dash
tangem/blockchain-sdk-kotlin-old pull request #107
Opened 2022-09-05 07:25 UTC by osthost1989

And 1784 add dash

2022-09-09 11:50 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +//                DashWalletManager(
закоменченные строки стоит удалить

2022-09-09 11:51 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +//                DashWalletManager(
Думаю, коммент можно удалить

2022-09-09 11:51 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +    Dash("DASH","DASH","Dash"),
Пробелы после запятых пропустил)

2022-09-09 11:56 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +        Dash -> "http://faucet.test.dash.crowdnode.io/$address"
Не так получилось, посмотри в ПР с айоса повнимательней, если будут вопросы, говори.

2022-09-09 11:58 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +        Dash -> "http://faucet.test.dash.crowdnode.io/$address"
Dash -> "http://faucet.test.dash.crowdnode.io/$address"
Это не отсюда

DashTestNet -> "https://blockexplorer.one/dash/$address"  это надо в разные адреса для тестнета и мэйннета переделать

2022-09-09 12:02 UTC, roman-pv requested changes

2022-09-09 12:02 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
Эту функцию нужно проапдейтить для нового блокчейна `fun getTestnetVersion(): Blockchain? {`

2022-09-09 12:02 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +            Bitcoin, Ducatus, Dash -> 0
Посмотри внимательней в iOS, там другой cointype

2022-09-12 08:56 UTC, osthost1989 commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +        Dash -> "http://faucet.test.dash.crowdnode.io/$address"
Done

2022-09-12 08:59 UTC, osthost1989 commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
Done

2022-09-12 09:13 UTC, osthost1989 commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +            Bitcoin, Ducatus, Dash -> 0
Done

2022-09-12 09:14 UTC, osthost1989 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +//                DashWalletManager(
Done

2022-09-12 09:14 UTC, osthost1989 commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +    Dash("DASH","DASH","Dash"),
Done

2022-09-12 09:14 UTC, osthost1989 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +//                DashWalletManager(
Done

2022-09-12 15:23 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +    DashTestNet("DASH/test", "DASH", "Dash Testnet"),
DashTestNet -> DashTestnet

2022-09-12 15:33 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinAddressService.kt
> +        Blockchain.Dash -> DashMainNetParams()
Мы добавляем DashTestnet в список блокчйенов, но здесь здесь он не указан. Получается, что мы не сможем создать DashTestnet walletManager. Для тестнета другие параметры нужны?

2022-09-12 15:34 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTransactionBuilder.kt
> +        Blockchain.Dash -> DashMainNetParams()
DashTestnet - такая же ситуация, как и с BitcoinAddressService

2022-09-12 15:38 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +            Blockchain.Bitcoin, Blockchain.BitcoinTestnet, Blockchain.Dogecoin, Blockchain.Dash ->
не хватает DashTestnet

2022-09-12 15:38 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/network/blockchair/BlockchairNetworkProvider.kt
> +            Blockchain.Dash -> "dash/"
не хватает DashTestnet

2022-09-12 15:38 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/network/blockcypher/BlockcypherNetworkProvider.kt
> +            Blockchain.Dash -> "dash/"
не хватает DashTestnet

2022-09-13 16:28 UTC, osthost1989 commented on blockchain/src/main/java/com/tangem/blockchain/network/blockcypher/BlockcypherNetworkProvider.kt
> +            Blockchain.Dash -> "dash/"
Done

2022-09-13 16:28 UTC, osthost1989 commented on blockchain/src/main/java/com/tangem/blockchain/network/blockchair/BlockchairNetworkProvider.kt
> +            Blockchain.Dash -> "dash/"
Done

2022-09-13 16:28 UTC, osthost1989 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +            Blockchain.Bitcoin, Blockchain.BitcoinTestnet, Blockchain.Dogecoin, Blockchain.Dash ->
Done

2022-09-13 16:28 UTC, osthost1989 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTransactionBuilder.kt
> +        Blockchain.Dash -> DashMainNetParams()
Done

2022-09-13 16:28 UTC, osthost1989 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinAddressService.kt
> +        Blockchain.Dash -> DashMainNetParams()
Done

2022-09-13 16:28 UTC, osthost1989 commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +    DashTestNet("DASH/test", "DASH", "Dash Testnet"),
Done

2022-09-13 17:08 UTC, gbixahue submitted a review, later dismissed

2022-09-15 07:12 UTC, roman-pv approved these changes, later dismissed

2022-09-19 13:58 UTC, roman-pv submitted a review, later dismissed

2022-09-19 16:27 UTC, lazutkin-andrey approved these changes, later dismissed

2022-09-19 18:01 UTC, lazutkin-andrey approved these changes

2022-09-19 18:01 UTC, merged