AND-3247 Block with pending transaction does not appear for BTC-like …
tangem/blockchain-sdk-kotlin-old pull request #170
Opened 2023-03-30 12:46 UTC by MamaLemon

…blockchains with Nownodes/Getblock APIs

2023-03-30 14:47 UTC, kozarezvlad submitted a review, later dismissed

2023-03-31 07:21 UTC, Yoggam1 requested changes

2023-03-31 07:21 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/network/blockbook/BlockBookNetworkProvider.kt
> +                        address = address
Тут видимо забыл про trailing comma

2023-03-31 07:21 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/network/blockbook/BlockBookNetworkProvider.kt
> +                    isConfirmed = false
Тут видимо забыл про trailing comma

2023-03-31 07:31 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/network/blockbook/BlockBookNetworkProvider.kt
> +                        address = address
С trailing comma - спорный момент. Это добавлено в кодстайл проекта, поэтому иногда проставляется, иногда нет, несмотря на то, что я постоянно прогоняю кодстайл в проекте. Но не думаю, что это должно быть каким-то обязательным требованием кодстайла.

2023-03-31 07:36 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/network/blockbook/BlockBookNetworkProvider.kt
> +                    .vout.firstOrNull()
Может так красивше?
```
var balanceDif = transaction.vout.firstOrNull()
    ?.value?.toBigDecimalOrNull()
    ?.movePointLeft(blockchain.decimals())
    ?: return@mapNotNull null
```

2023-03-31 07:48 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/network/blockbook/BlockBookNetworkProvider.kt
> +                    .vout.firstOrNull()
Как мне кажется, это все дело вкуса и закреплять требование кодстайла касательно таких ситуация очень проблематично.
В моем случае, я пытался сделать так, чтобы цепочка вызовов была максимально читаемая, поэтому с каждой строчки сделал какое-то логическое действие:
1) Достать из массива vout первый эл-т
2) Достать значение и привести в большому значению
3) ....

2023-03-31 08:10 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/network/blockbook/BlockBookNetworkProvider.kt
> +                        address = address
> Но не думаю, что это должно быть каким-то обязательным требованием кодстайла.

> С trailing comma - спорный момент.
Такие спорные моменты лучше уж обсуждать не в рамках ПРа, а в отдельным топиком. А сейчас, если в кодстайле есть такое требование, то надо его соблюдать.

2023-03-31 09:22 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/network/blockbook/BlockBookNetworkProvider.kt
> +                        address = address
Добавил

2023-03-31 09:22 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/network/blockbook/BlockBookNetworkProvider.kt
> +                    isConfirmed = false
Добавил

2023-03-31 09:46 UTC, Yoggam1 approved these changes

2023-03-31 10:04 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/network/blockbook/BlockBookNetworkProvider.kt
> +                    .vout.firstOrNull()
С делом вкуса согласен, и что закреплять сложно - согласен.
Но вот с _1. Достать из массива vout первый эл-т_ :
в твоем случае получается, что в строке var balanceDif = transaction ничего не делается, хотя должен быть пункт 1, как ты описал.

Но, дело вкуса... я всего лишь предложил рассмотреть вариант.

2023-03-31 10:04 UTC, gbixahue approved these changes

2023-03-31 10:50 UTC, merged