AND-3151 TON integration
tangem/blockchain-sdk-kotlin-old pull request #171
Opened 2023-03-31 07:09 UTC by Yoggam1

2023-03-31 09:43 UTC, kozarezvlad requested changes

2023-03-31 09:43 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonJsonRpcClientBuilder.kt
> +        val url = if (isTestNet) "https://testnet.toncenter.com/api/v2/" else "https://toncenter.com/api/v2/"
Не крит. Мб положить это константами в TonJsonRpcNetworkProvider? либо все адреса на тон сложить в один companion чтобы рядом лежали если поменять попросят что то

2023-03-31 09:43 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonTransactionBuilder.kt
> +    var sequenceNumber: Int = 0
а он где инкрементится?

2023-03-31 09:43 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonTransactionBuilder.kt
> +    var sequenceNumber: Int = 0
Если снаружи в walletManager, предлагаю TonTransactionBuilder сделать stateless и в методах input передавать sequenceNumber снаружи.

2023-03-31 09:43 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            val type = Types.newParameterizedType(TonProviderResponse::class.java, TonGetWalletInfoResponse::class.java)
предлагаю не создавать каждый раз в методе, а вынести на уровень поля объекта

2023-03-31 09:43 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            val jsonAdapter = moshi.adapter<TonProviderResponse<TonGetWalletInfoResponse>>(type)
и адаптер

2023-03-31 09:43 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            val type = Types.newParameterizedType(TonProviderResponse::class.java, TonGetFeeResponse::class.java)
аналогично как выше

2023-03-31 09:43 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            val type = Types.newParameterizedType(TonProviderResponse::class.java, TonSendBocResponse::class.java)
и тут

2023-03-31 15:30 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            val type = Types.newParameterizedType(TonProviderResponse::class.java, TonGetFeeResponse::class.java)
исправил

2023-03-31 15:30 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonTransactionBuilder.kt
> +    var sequenceNumber: Int = 0
исправил

2023-03-31 15:30 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            val type = Types.newParameterizedType(TonProviderResponse::class.java, TonGetWalletInfoResponse::class.java)
исправил

2023-03-31 15:30 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            val jsonAdapter = moshi.adapter<TonProviderResponse<TonGetWalletInfoResponse>>(type)
исправил

2023-03-31 15:31 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            val type = Types.newParameterizedType(TonProviderResponse::class.java, TonSendBocResponse::class.java)
исправил

2023-03-31 15:32 UTC, kozarezvlad submitted a review, later dismissed

2023-03-31 15:35 UTC, kozarezvlad submitted a review, later dismissed

2023-03-31 15:52 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonJsonRpcClientBuilder.kt
> +object TonJsonRpcClientBuilder {
Тут не нужен object. Пару раз используется, а висеть в памяти будет вечно

2023-03-31 15:52 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonWalletManager.kt
> +        if (info.sequenceNumber != txBuilder.sequenceNumber) {
Странное условие для того, чтобы пометить все отправленные транзакции, как подтвержденные.
А что такое `sequenceNumber` в Тон кошельке?
А не имеет значение разница этих значение если одно из > или < ?

2023-03-31 15:52 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonTransactionBuilder.kt
> +    val publicKey = CryptoUtils.generatePublicKey(privateKey)
Ты создаешь `publicKey` для Secp256k1, а не для Ed25519

2023-03-31 15:52 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonApi.kt
> +)
Дефолтные поля лучше класть в конец, иначе всегда придется разыменовывать поля `method` и `params`  в объекте при создании.

2023-03-31 15:52 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            return Result.Success(getWalletInfoResponse.result)
Очень сложно читается... лишние return.
Можно переписать таким образом
```
if (getWalletInfoResponse.ok) {
    Result.Success(getWalletInfoResponse.result)
} else {
    val error = BlockchainSdkError.Ton(
        subCode = getWalletInfoResponse.code ?: 0,
        customMessage = getWalletInfoResponse.error.orEmpty()
    )
    Result.Failure(error)
}
```

2023-03-31 15:52 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            return Result.Success(getFeeResponse.result)
И здесь можно упростить

2023-03-31 15:52 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            return Result.Success(sendBocResponse.result)
И здесь можно упростить

2023-03-31 15:52 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonNetworkModels.kt
> +    ;
`;` - можно убрать

2023-03-31 15:52 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonNetworkService.kt
> +            return Result.Success(
Лишний return

2023-03-31 15:52 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonNetworkService.kt
> +            return Result.Success(
Лишний return

2023-03-31 15:52 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonNetworkService.kt
> +            return Result.Success(hashResponse.hash)
Лишний return

2023-03-31 16:15 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonJsonRpcClientBuilder.kt
> +object TonJsonRpcClientBuilder {
Тут же статичные функции, без стейта, почему не использовать объект? Что ты предлагаешь вместо?

2023-03-31 16:25 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletCoreSigner.kt
> +        return PublicKey(publicKey.blockchainKey, PublicKeyType.ED25519)
В таком виде это не универсальный Signer, тут конкретная кривая выбрана и в методе sign один хэш на подпись только

2023-04-01 07:40 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonTransactionBuilder.kt
> +    val publicKey = CryptoUtils.generatePublicKey(privateKey)
@Yoggam1 Тут в целом extension Ed25519 лишний

2023-04-01 11:53 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletCoreSigner.kt
> +        return (signResult as CompletionResult.Success).data
Здесь будем крашить, если sdkSigner вернут CompletionResult.Failure.
Самый простой пример - поднести не ту карту.

2023-04-01 11:55 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonJsonRpcClientBuilder.kt
> +object TonJsonRpcClientBuilder {
Обычный класс

2023-04-02 21:41 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonJsonRpcClientBuilder.kt
> +object TonJsonRpcClientBuilder {
Исправил

2023-04-02 22:26 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonWalletManager.kt
> +        if (info.sequenceNumber != txBuilder.sequenceNumber) {
блокчейн не дает нам возможности проверить статус транзакции. Поэтому условно подтверждаем транзакцию(как в случае бинанса, стеллар). А sequenceNumber это что-то вроде блока. Если он различается от последнего нам известного(то появился новый блок в блокчейне), то апдейтим статус транзакции.

2023-04-02 22:31 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonTransactionBuilder.kt
> +    val publicKey = CryptoUtils.generatePublicKey(privateKey)
исправил

2023-04-02 22:31 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonApi.kt
> +)
исправил

2023-04-02 22:32 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            return Result.Success(getWalletInfoResponse.result)
исправил

2023-04-02 22:32 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            return Result.Success(getFeeResponse.result)
исправил

2023-04-02 22:33 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            return Result.Success(sendBocResponse.result)
исправил

2023-04-02 22:33 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonNetworkModels.kt
> +    ;
исправил

2023-04-02 22:34 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonNetworkService.kt
> +            return Result.Success(
исправил

2023-04-02 22:34 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonNetworkService.kt
> +            return Result.Success(
исправил

2023-04-02 22:34 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonNetworkService.kt
> +            return Result.Success(hashResponse.hash)
исправил

2023-04-02 22:41 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletCoreSigner.kt
> +        return PublicKey(publicKey.blockchainKey, PublicKeyType.ED25519)
исправил type.

А насчёт хэша, в стороне wallet-core еще нету такой функциональности где бы он отправлял массив хэшов.

2023-04-02 23:14 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletCoreSigner.kt
> +        return (signResult as CompletionResult.Success).data
Про этот случай известен. Уже создан баг и исправлю в скоупе того бага. Давай пока это оставим как есть, так как это требует изменений еще в wallet-core. Я уже работаю над этим

2023-04-03 07:36 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            Result.Success(getFeeResponse.result)
Куда-то делось мое сообщение... 
Я предлагаю переделать данный участок кода на
```
if (getFeeResponse.ok) {
    Result.Success(getFeeResponse.result)
} else {
    val error = BlockchainSdkError.Ton(
        subCode = getFeeResponse.code ?: 0,
        customMessage = getFeeResponse.error.orEmpty(),
    )
    Result.Failure(error)
}
```

В этом варианте if пляшет от позитивного условия и улучшена структура для облегчения понимания

2023-04-03 07:36 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            Result.Success(sendBocResponse.result)
Предлагаю переделать так-же, как обозначил выше

2023-04-03 07:40 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonWalletManager.kt
> +        if (info.sequenceNumber != txBuilder.sequenceNumber) {
Ясно

2023-04-03 09:17 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/common/BlockchainSdkConfig.kt
> +        const val xApiKeyHeader = "x-api-key"
Предлагаю использовать нейминг из конвенций котлина - screaming snake case

2023-04-03 09:21 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonJsonRpcClientBuilder.kt
> +            blockchainSdkConfig.tonCenterCredentials?.let { add(createTonCenterJsonRpcProvider(isTestNet, it)) }
Необходимо добавить проверки на пустоту апи ключа, иначе если в конфиге окажется пустая строка, то добавится невалидный провайдер

2023-04-03 09:26 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            val getWalletInfoResponse = walletInfoAdapter.fromJson(response.string())!!
Предлагаю использовать функцию requireNotNull() с указанием текста ошибки, если все-таки распарситься не сможет

2023-04-03 09:27 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            if (!getWalletInfoResponse.ok) Result.Failure(
Хорошо бы использовать синтаксис фигурные скобки, так как конструкция многострочная вышла

2023-04-03 09:30 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +    class Ton(
По названию ошибки не совсем ясно ее предназначение, предлагаю переименовать

2023-04-03 09:30 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletCoreSigner.kt
> +                // throw signResult.error
Можно удалить?

2023-04-03 09:31 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/network/JsonAdapters.kt
> +internal object BigDecimalAdapter : JsonAdapter<BigDecimal>() {
Вроде что-то было уже добавлено для данного типа данных. Оно не подходит?

2023-04-03 11:37 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletCoreSigner.kt
> +                // throw signResult.error
Удалять точно не надо, потому что тогда в случае ошибки мы будем возвращать пустой хэш. Мне кажется, нам надо сделать свою обертку над их сайнером, чтобы можно было и несколько хэшей сразу подписывать, и ошибки обрабатывать и возвращать Result, а не throwable функцией пользоваться. Надо это все продумать, потому что пока не выглядит удобным классом для дальнейшего использования

2023-04-03 12:29 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/network/JsonAdapters.kt
> +internal object BigDecimalAdapter : JsonAdapter<BigDecimal>() {
Я такого не нашел. Если знаешь где добавлено точно, поделись

2023-04-03 12:33 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            Result.Success(getFeeResponse.result)
исправил

2023-04-03 12:33 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            Result.Success(sendBocResponse.result)
исправил

2023-04-03 12:34 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/BlockchainSdkConfig.kt
> +        const val xApiKeyHeader = "x-api-key"
исправил

2023-04-03 12:34 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            if (!getWalletInfoResponse.ok) Result.Failure(
исправлен

2023-04-03 12:40 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/network/TonJsonRpcNetworkProvider.kt
> +            val getWalletInfoResponse = walletInfoAdapter.fromJson(response.string())!!
исправил

2023-04-03 12:43 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +    class Ton(
Точно. Исправил

2023-04-03 12:44 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletCoreSigner.kt
> +                // throw signResult.error
Спасибо что напомнил. Удалил

2023-04-03 12:51 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonJsonRpcClientBuilder.kt
> +            blockchainSdkConfig.tonCenterCredentials?.let { add(createTonCenterJsonRpcProvider(isTestNet, it)) }
Исправил

2023-04-03 13:22 UTC, gbixahue approved these changes

2023-04-03 13:24 UTC, roman-pv approved these changes

2023-04-03 13:50 UTC, kozarezvlad approved these changes

2023-04-03 13:50 UTC, merged