AND-3358 added new tron APIs
tangem/blockchain-sdk-kotlin-old pull request #180
Opened 2023-04-10 13:03 UTC by kozarezvlad

2023-04-11 16:22 UTC, Yoggam1 requested changes

2023-04-11 16:22 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +                    list.add(TronNetwork.TronGrid(null))
этот network точно нужен?

2023-04-11 16:22 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +                    val list = mutableListOf<TronNetwork>()
Можно заюзать `buildList`

2023-04-11 16:38 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +                    list.add(TronNetwork.TronGrid(null))
видимо да, в ios по крайней мере добавили такой вариант без apiKey, уточню у Андрея

2023-04-12 06:43 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/tron/network/TronJsonRpcNetworkProvider.kt
> +        val headerInterceptors = if (network is TronNetwork.TronGrid && network.apiKey != null) {
Хорошо бы проверить апи ключ на пустоту

2023-04-12 06:44 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/tron/network/TronNetwork.kt
> +        const val TRON_GRID_API_HEADER_NAME = "TRON-PRO-API-KEY"
Кажется, что это только косвенно относится к данному классу. Мб вынести сразу в провайдер, где непосредственно нужна данная константа

2023-04-12 07:37 UTC, Yoggam1 submitted a review, later dismissed

2023-04-12 08:26 UTC, MamaLemon approved these changes, later dismissed

2023-04-12 09:05 UTC, Yoggam1 submitted a review, later dismissed

2023-04-12 09:07 UTC, roman-pv submitted a review, later dismissed

2023-04-12 10:33 UTC, Yoggam1 approved these changes

2023-04-12 10:34 UTC, iiiburnyiii approved these changes

2023-04-12 10:49 UTC, merged