AND-3356 new cardano API
tangem/blockchain-sdk-kotlin-old pull request #181
Opened 2023-04-10 13:50 UTC by kozarezvlad

2023-04-11 16:17 UTC, Yoggam1 requested changes

2023-04-11 16:17 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +                        config.getBlockCredentials?.apiKey ?: ""
Если apiKey нету. то может лучше не добавлять такой провайдер?

2023-04-11 16:37 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +                        config.getBlockCredentials?.apiKey ?: ""
что то проглядел, вроде выносил это в let, поправлю

2023-04-12 06:41 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/network/RosettaNetwork.kt
> +sealed class RosettaNetwork(val url: String) {
Мб назвать лучше Cardano вместо Rosetta?

2023-04-12 07:00 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/network/RosettaNetwork.kt
> +sealed class RosettaNetwork(val url: String) {
Но это API ведь именно Rosetta называется
https://www.rosetta-api.org/docs/1.4.4/welcome.html

2023-04-12 07:12 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +                        config.getBlockCredentials?.apiKey ?: ""
поправил

2023-04-12 07:38 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/network/RosettaNetwork.kt
> +sealed class RosettaNetwork(val url: String) {
Если я правильно понимаю контекст, то данный класс объединяет в себе мета данные для разных провайдеров, одним из которых является розетта. Поэтому я и предложил назвать это CordanoNetwork

2023-04-12 07:38 UTC, Mama1emon approved these changes

2023-04-12 07:41 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/network/RosettaNetwork.kt
> +sealed class RosettaNetwork(val url: String) {
Нет, этот класс объединяет лишь данные для провайдера Rosetta

2023-04-12 07:44 UTC, MamaLemon approved these changes

2023-04-12 09:07 UTC, roman-pv approved these changes

2023-04-12 09:45 UTC, Yoggam1 approved these changes

2023-04-12 09:45 UTC, merged