Add cosmos support
tangem/blockchain-sdk-kotlin-old pull request #200
Opened 2023-05-02 13:13 UTC by Yoggam1

2023-05-02 19:29 UTC, kozarezvlad requested changes

2023-05-02 19:29 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosAccountInfo.kt
> +    val accountNumber: Long?,
это типа memo в ton'е? может не быть?
хотя ниже вижу memo, тогда не совсем понятно что тут. Допили плз доку на поля

2023-05-02 19:29 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosTransactionBuilder.kt
> +        feeAmount: Amount?,
а почему это nullable? может отбивать ошибку на более раннем этапе если fee нету?

2023-05-02 19:29 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosWalletManager.kt
> +        // Transactions are confirmed instantaneously
это особенность блокчейна?

2023-05-02 19:29 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/network/CosmosApi.kt
> +    @GET("/cosmos/auth/v1beta1/accounts/{address}")
лучше убрать тут / и добавить в конец baseUrl иначе ретрофит обрезает всё после хоста

2023-05-02 19:29 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +                        add("https://rest.cosmos.directory/cosmoshub")
отписал выше, тут тоже отмечу. Надо добавить / в конец адреса и убрать в интерфейсе api в аннотации. Тут /cosmoshub будет обрезан ретрофитом

2023-05-02 19:29 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +                        add("https://cosmoshub-api.lavenderfive.com")
ну и тут везде добавить /

2023-05-02 20:11 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosWalletManager.kt
> +        // Transactions are confirmed instantaneously
Да

2023-05-02 20:13 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosTransactionBuilder.kt
> +        feeAmount: Amount?,
fee может быть nullable. Это используется когда надо симулировать транзакцию чтобы посчитать комиссию/газ и т.д. И тут не надо отбивать ошибку

2023-05-02 20:16 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosAccountInfo.kt
> +    val accountNumber: Long?,
Нет, это не мемо. Мемо используется в TransactionBuilder`е. Это номер аккаунта. Обычно, мемо идет в направлении блокчейна, а тут мы берем номер аккаунта из блокчейна. Тоже используется внутри TransactionBuilder

2023-05-03 06:57 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/network/CosmosApi.kt
> +    @GET("/cosmos/auth/v1beta1/accounts/{address}")
исправил

2023-05-03 06:57 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +                        add("https://rest.cosmos.directory/cosmoshub")
исправил

2023-05-03 06:57 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +                        add("https://cosmoshub-api.lavenderfive.com")
исправил

2023-05-03 07:00 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +            Cosmos -> "${baseUrl}/$address"
после baseUrl не нужен вроде слэш, он есть уже там внутри

2023-05-03 07:03 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +            Cosmos -> "${baseUrl}/$address"
Исправил

2023-05-03 07:03 UTC, kozarezvlad approved these changes, later dismissed

2023-05-03 07:29 UTC, MamaLemon approved these changes

2023-05-03 07:29 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosTransactionBuilder.kt
> +            .setPrivateKey(ByteString.copyFrom(CryptoUtils.generateRandomBytes(length = 32)))
Предлагаю сделать перенос аргументов на новую строчку, так как тяжело воспринимается три вызова функции в одной строке, но дело вкуса

2023-05-03 07:29 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/network/CosmosChain.kt
> +        override val gasPrices: List<Double> = throw IllegalStateException()
Как мне кажется, `gasPrices` не должен переопределяться для Gaia. Выглядит как нарушение принципа InterfaceSegregation. Либо я не до конца понял причину данной реализации

2023-05-03 07:29 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/network/CosmosChain.kt
> +    data class Cosmos(
Можно сигнатуру в одну строчку, но дело вкуса

2023-05-03 07:29 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/network/CosmosRestProvider.kt
> +                if (accountsResult.error is BlockchainSdkError.Cosmos.Api && accountsResult.error.code == 5) {
Хорошо бы вынести число в константы, так как из данного значения пока мало понятно, почему должно ровняться именно 5

2023-05-03 07:29 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/network/CosmosRestProvider.kt
> +            val request = sendRequestAdapter.fromJson(requestBody)!!
Хорошо бы использовать requireNotNull с комментом

2023-05-03 07:29 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/common/UnmarshalHelper.kt
> +internal class UnmarshalHelper {
А нужно ли именно объект данного функционала?
Я бы предложил сделать top level функцией или синглтоном

2023-05-03 07:29 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/extensions/CoinType.kt
> +internal val Blockchain.twCoinType: CoinType
А что из себя представляет данная сущность? Объединяет объект сети и тестнета одного блокчейна?

2023-05-03 07:32 UTC, MamaLemon requested changes

2023-05-03 07:32 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosWalletManager.kt
> +
Случайно апрувнул

2023-05-03 08:44 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/UnmarshalHelper.kt
> +internal class UnmarshalHelper {
Он используется только в двух местах. А какой смысл чтобы он висел как статик? К тому же @gbixahue попросил сделать такие вещи через классы

2023-05-03 08:46 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/extensions/CoinType.kt
> +internal val Blockchain.twCoinType: CoinType
Добавил доку

2023-05-03 08:48 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/network/CosmosRestProvider.kt
> +            val request = sendRequestAdapter.fromJson(requestBody)!!
Исправил

2023-05-03 08:49 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/network/CosmosChain.kt
> +    data class Cosmos(
Давай оставим как есть. В след ПРе будет переделан все равно

2023-05-03 08:49 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosTransactionBuilder.kt
> +            .setPrivateKey(ByteString.copyFrom(CryptoUtils.generateRandomBytes(length = 32)))
Исправил

2023-05-03 08:51 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/network/CosmosRestProvider.kt
> +                if (accountsResult.error is BlockchainSdkError.Cosmos.Api && accountsResult.error.code == 5) {
Исправил

2023-05-03 09:14 UTC, MamaLemon commented on blockchain/src/main/java/com/tangem/blockchain/common/UnmarshalHelper.kt
> +internal class UnmarshalHelper {
Просто название хелпер немного зацепило, так как "помощник" имеет слишком общее назначение.
Но если никто больше не отреагировал, то мб дело вкуса

2023-05-03 09:14 UTC, Mama1emon approved these changes

2023-05-03 09:40 UTC, kozarezvlad approved these changes

2023-05-03 09:52 UTC, merged