AND-3490 Add sender/receiver address for RVN
tangem/blockchain-sdk-kotlin-old pull request #204
Opened 2023-05-14 20:26 UTC by Yoggam1

2023-05-14 20:27 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/extensions/Coroutines.kt
> +                is BlockchainSdkError.Cosmos.Api -> true
К текущему таску не имеет значения. Заметил что они отсутствуют и добавил.

2023-05-15 08:56 UTC, Mama1emon requested changes

2023-05-15 08:56 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ravencoin/RavencoinWalletManager.kt
> +            amount = Amount(wallet.amounts[AmountType.Coin]!!, this.balanceDif.abs()),
Хорошо бы использовать функцию для `getOrNull()` с безопасной обработкой

2023-05-15 08:56 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ravencoin/RavencoinWalletManager.kt
> +            if (confirmedTransactions.find { confirmed ->
Как мне кажется, если вынести `confirmedTransactions.find { confirmed -> confirmed.hash.equals(recent.hash, true) }` в локальную переменную, то код будет читаться легче. Но не крит, на твое усмотрение

2023-05-15 15:16 UTC, kozarezvlad submitted a review, later dismissed
Апрув с учетом коммента про getOrNull()

2023-05-19 06:03 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ravencoin/RavencoinWalletManager.kt
> +            amount = Amount(wallet.amounts[AmountType.Coin]!!, this.balanceDif.abs()),
Исправил

2023-05-19 06:04 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ravencoin/RavencoinWalletManager.kt
> +            if (confirmedTransactions.find { confirmed ->
Сделал

2023-05-19 06:23 UTC, Mama1emon approved these changes

2023-05-19 06:57 UTC, kozarezvlad approved these changes

2023-05-19 06:57 UTC, merged