Feature/AND-3312_add_transactionfee_entity
tangem/blockchain-sdk-kotlin-old pull request #215
Opened 2023-05-29 17:16 UTC by Sateetas

2023-05-30 07:17 UTC, Mama1emon requested changes

2023-05-30 07:17 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosWalletManager.kt
> +                    return Result.Success(TransactionFee.Choosable(amounts[0], amounts[1], amounts[2]))
Предлагаю return сделать общий. Странно, что студия не подсветила

2023-05-30 07:17 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/EthereumWalletManager.kt
> +
Лишняя строка?

2023-05-30 07:17 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/EthereumWalletManager.kt
> +        return Amount(wallet.amounts[AmountType.Coin]!!, bigDecimal.toBigDecimal(
Предлагаю использовать requireNotNull с явным сообщением

2023-05-30 07:17 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/transaction/TransactionFee.kt
> +
Лишняя строка?

2023-05-30 07:17 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/transaction/TransactionFee.kt
> +    data class Single(
Можно в одну строчку, но дело вкуса

2023-05-30 10:10 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosWalletManager.kt
> +                    return Result.Success(TransactionFee.Choosable(amounts[0], amounts[1], amounts[2]))
ага, поправил

2023-05-30 10:15 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/transaction/TransactionFee.kt
> +    data class Single(
не, тут как минимум консистентно с предыдущим получается

2023-05-30 10:16 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/transaction/TransactionFee.kt
> +
нет, специально пустая строка перед закрывающей скобкой класса

2023-05-30 10:18 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/EthereumWalletManager.kt
> +        return Amount(wallet.amounts[AmountType.Coin]!!, bigDecimal.toBigDecimal(
ага

2023-05-30 14:12 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/EthereumWalletManager.kt
> +
ага, убрал

2023-05-31 04:06 UTC, Mama1emon commented on blockchain-demo/src/main/java/com/tangem/blockchain_demo/BlockchainDemoActivity.kt
>  //                        btnSend.isEnabled = true
Можно удалить?

2023-05-31 04:06 UTC, Mama1emon commented on blockchain-demo/src/main/java/com/tangem/blockchain_demo/BlockchainDemoActivity.kt
> +                                selectedFee = fees.value.value ?: BigDecimal(0)
Не совсем информативно получается - `fees.value.value`. Мб как-нибудь переименовать `fees.value`?

2023-05-31 04:06 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/CardanoWalletManager.kt
> +            TransactionData(amount, null, wallet.address, destination)
Как мне кажется, именованные аргументы здесь бы не помешали

2023-05-31 04:06 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/optimism/OptimismWalletManager.kt
> +            minimum = layer2fee.minimum + lastLayer1Fee.value!!,
requireNotNull()?

2023-05-31 04:06 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/optimism/OptimismWalletManager.kt
> +            minimum = layer2fee.minimum + lastLayer1Fee.value!!,
requireNotNull()?

2023-06-01 15:31 UTC, Sateetas commented on blockchain-demo/src/main/java/com/tangem/blockchain_demo/BlockchainDemoActivity.kt
>  //                        btnSend.isEnabled = true
готово

2023-06-01 15:31 UTC, Sateetas commented on blockchain-demo/src/main/java/com/tangem/blockchain_demo/BlockchainDemoActivity.kt
> +                                selectedFee = fees.value.value ?: BigDecimal(0)
переименовал в `normal`

2023-06-01 15:31 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/optimism/OptimismWalletManager.kt
> +            minimum = layer2fee.minimum + lastLayer1Fee.value!!,
ага

2023-06-01 15:32 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/optimism/OptimismWalletManager.kt
> +            minimum = layer2fee.minimum + lastLayer1Fee.value!!,
ага

2023-06-02 12:03 UTC, Yoggam1 requested changes

2023-06-02 12:03 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/stellar/StellarWalletManager.kt
>          ))
```suggestion
        return Result.Success(
            TransactionFee.Choosable(
                minimum = Amount(minChargedFee, blockchain),
                normal = Amount(averageChargedFee, blockchain),
                priority = Amount(maxChargedFee, blockchain),
            )
        )
```

2023-06-02 12:03 UTC, Yoggam1 commented
TransactionExtras потом сделаешь?

2023-06-02 12:09 UTC, Sateetas commented
> FeeExtras потом сделаешь?

ага, обсудил с айос-командой, решили сделать так

но я пока не запушил это

<img width="334" alt="image" src="https://github.com/tangem/blockchain-sdk-kotlin/assets/13484957/fb675217-0455-41d5-b182-d703f8706537">

2023-06-07 05:09 UTC, iiiburnyiii requested changes

2023-06-07 05:09 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinWalletManager.kt
> +                    val newAmount =  amount.copy(value = amount.value!! - feeValue)
Думаю стоит добавить сообщение к возможной ошибке через `requireNotNull`

2023-06-07 05:09 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosWalletManager.kt
> +                return if (amounts.size == 3) {
Кажется тут стоит обработать сценарий с другим количеством `amounts` 
```suggestion
                return when (amounts.size) {
                    1 -> Result.Success(TransactionFee.Single(amounts[0]))
                    3 -> Result.Success(TransactionFee.Choosable(amounts[0], amounts[1], amounts[2]))
                    else -> Result.Error(IllegalStateException("Illegal amounts size"))
                }
```

2023-06-07 05:09 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/optimism/OptimismWalletManager.kt
> +            minimum = layer2fee.minimum + requireNotNull(lastLayer1Fee.value),
Думаю стоит сообщение добавить, а то получается, что нет различия с `!!`

```suggestion
            minimum = layer2fee.minimum + requireNotNull(lastLayer1Fee.value) { "Last layer 1 fee must not be null" },
```

2023-06-07 05:09 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/optimism/OptimismWalletManager.kt
> +            minimum = layer2fee.minimum + requireNotNull(lastLayer1Fee.value),
Тут тож стоит сообщение добавить

2023-06-13 12:49 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinWalletManager.kt
> +                    val newAmount =  amount.copy(value = amount.value!! - feeValue)
готово в https://github.com/tangem/blockchain-sdk-kotlin/pull/218

2023-06-13 12:53 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosWalletManager.kt
> +                return if (amounts.size == 3) {
готово в https://github.com/tangem/blockchain-sdk-kotlin/pull/218

2023-06-13 13:28 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/optimism/OptimismWalletManager.kt
> +            minimum = layer2fee.minimum + requireNotNull(lastLayer1Fee.value),
готово в https://github.com/tangem/blockchain-sdk-kotlin/pull/218

2023-06-13 13:28 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/optimism/OptimismWalletManager.kt
> +            minimum = layer2fee.minimum + requireNotNull(lastLayer1Fee.value),
готово в https://github.com/tangem/blockchain-sdk-kotlin/pull/218

2023-06-15 12:32 UTC, Mama1emon approved these changes

2023-06-15 12:43 UTC, iiiburnyiii approved these changes

2023-06-15 16:02 UTC, merged