AND-3645: send events when switching network providers
tangem/blockchain-sdk-kotlin-old pull request #229
Opened 2023-06-16 13:18 UTC by roman-pv

2023-06-19 11:01 UTC, Sateetas requested changes

2023-06-19 11:01 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/stellar/StellarNetworkService.kt
> +    exceptionHandler: ExternalExceptionHandler?,
почему nullable? и в других нетворк сервисах тоже

2023-06-19 11:01 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/extensions/Coroutines.kt
> +        is Result.Success -> this.getEthereumErrorMessage()
очень неочевидная реализация для такого названия метода

может, переназвать метод по-другому? 
и в идеале вынести его в класс по месту использования

2023-06-19 11:24 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/stellar/StellarNetworkService.kt
> +    exceptionHandler: ExternalExceptionHandler?,
потому что мы хотим оставить возможность не использовать ExternalExceptionHandler

2023-06-19 11:25 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/extensions/Coroutines.kt
> +        is Result.Success -> this.getEthereumErrorMessage()
какое название будет очевидным? мы получаем текст ошибки из класса result

2023-06-19 14:24 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/extensions/Coroutines.kt
> +        is Result.Success -> this.getEthereumErrorMessage()
1) нужно найти для него (для метода `fun Result<*>.getErrorMessage()`) подходящее по смыслу название, что-то вроде `tryExtractEthereumErrorMessage`. 
текущее название метода не отображает суть и может привести к смысловым коллизиям


2) нужно вынести его из файла `Coroutines.kt`, по месту его использования, потому что в `Coroutines.kt` расположены общие вещи, мы здесь не должны в частности лезть вроде `(this.data as? EthereumResponse)?.error?.message`. 

метод `private fun Result.Success<*>.getEthereumErrorMessage()` тоже нужно вынести по месту его использования

2023-06-19 14:26 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/stellar/StellarNetworkService.kt
> +    exceptionHandler: ExternalExceptionHandler?,
окей, тогда подсунем stub-implementation

2023-06-19 14:32 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/extensions/Coroutines.kt
> +        is Result.Success -> this.getEthereumErrorMessage()
сорри за конфьюз, мой первый коммент в этом треде относится к методу `fun Result<*>.getErrorMessage()`, а не к `getEthereumErrorMessage()`

2023-06-20 03:06 UTC, Mama1emon requested changes

2023-06-20 03:06 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/network/EthereumJsonRpcProvider.kt
> +    override val host: String = baseUrl
Мб принимать в конструкторе не `baseUrl: String`, а `override val host: String`?

2023-06-20 03:06 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/polkadot/network/PolkadotNetworkService.kt
> +            val info = AccountRequests.balanceOf(address).execute(polkadotApi).get() //todo check
?

2023-06-20 03:06 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/stellar/StellarNetworkService.kt
> +internal const val RECORD_LIMIT = 200
Подскажи, пожалуйста, где еще используется данная константа?

2023-06-20 03:06 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/stellar/StellarWrapperNetworkProvider.kt
> +class StellarWrapperNetworkProvider(
На мой взгляд, можно опустить слово `Wrapper`

2023-06-20 03:06 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ton/TonWalletManager.kt
> +        blockchain = wallet.blockchain)
Хорошо бы скобку перенести на новую строчку

2023-06-20 03:06 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/network/MultiNetworkProvider.kt
> +            if (!result!!.isResultNetworkError()) {
Есть ли 100% гарантия, что NPE никогда не выбросится?

2023-07-04 14:49 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/stellar/StellarNetworkService.kt
> +internal const val RECORD_LIMIT = 200
StellarWrapperNetworkProvider

2023-07-04 14:49 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/polkadot/network/PolkadotNetworkService.kt
> +            val info = AccountRequests.balanceOf(address).execute(polkadotApi).get() //todo check
Не актуально

2023-07-04 14:50 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/stellar/StellarWrapperNetworkProvider.kt
> +class StellarWrapperNetworkProvider(
StellarNetworkProvider уже есть, интерфейс. А это -  обертка над либой

2023-07-04 14:53 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/network/MultiNetworkProvider.kt
> +            if (!result!!.isResultNetworkError()) {
Он строкой выше присваивается, метод возвращает не nullable, поэтому он не может быть null

2023-07-04 14:54 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/stellar/StellarNetworkService.kt
> +    exceptionHandler: ExternalExceptionHandler?,
Почему здесь будет лучше использовать не nullable? Nullable понятнее и нисколько здесь не мешает.

2023-07-07 10:32 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosWalletManager.kt
> +import com.tangem.blockchain.common.Amount
опять что-то с настройками, то сворачиваем импорты, то разворачиваем...

2023-07-07 10:32 UTC, gbixahue commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/network/CosmosNetworkService.kt
> +    private val multiJsonRpcProvider = MultiNetworkProvider(providers, exceptionHandler)
Почему-то раньше не обращал на это внимание...
Мне кажется нам стоит подумать над тем, чтобы WalletManager'ы инициализировать сервисами, а не провадерами. А то сейчас мы провайдеры протягиваем через WalletManager, чтобы инициализировать им сервис.

Сейчас
```
class CosmosWalletManager(
    wallet: Wallet,
    networkProviders: List<CosmosRestProvider>,
    private val cosmosChain: CosmosChain,
) {
    private val networkService: CosmosNetworkService = CosmosNetworkService(networkProviders, cosmosChain)
}
```

Предлагаю
```
class CosmosWalletManager(
    wallet: Wallet,
    private val networkService: CosmosNetworkService,
    private val cosmosChain: CosmosChain,
) {
    
}
```

И такую же штуку сделать для NetworkService'ов... Чтобы они инициализировались не списком провайдеров, а сразу MultiNetworkProvider'ом - это избавит нас от протягивание и провайдеров и эксепшнХендлера.

2023-07-07 16:42 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/stellar/StellarNetworkService.kt
> +    exceptionHandler: ExternalExceptionHandler?,
nullable в целом ясности коду не добавляет

непонятно, нету потому что не удалось этот хендлер получить, или мб потому что он в целом не нужен?

и в DI ты не можешь запровайдить null

ты же уже создал интерфейс, почему бы по классике не сделать для него пару реализаций — реальную и стаб?

2023-07-19 10:03 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +import com.tangem.blockchain.common.assembly.impl.BinanceWalletManagerAssembly
Тут больше 5 не склеилось в *, проверь у себя настройки project codestyle

2023-07-19 10:05 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/network/MultiNetworkProvider.kt
> +            if (!result!!.isResultNetworkError()) {
можно создать локальную копию и не придется !! вызывать

2023-07-19 10:05 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/network/MultiNetworkProvider.kt
> +            is Result<*> -> ResultChecker.isNetworkError(result = this)
можно в один бренч объединить 128 и 129 строки

2023-07-19 10:05 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/network/MultiNetworkProvider.kt
> +            is Result<*> -> ResultChecker.getErrorMessageIfAvailable(result = this)
аналогично

2023-07-19 10:06 UTC, kozarezvlad reviewed
Общий вопрос, у нас ни одного провайдера где не используется MultiNetworkProvider? Кажется видел такие

2023-07-19 10:07 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/network/MultiNetworkProvider.kt
> +            is Result<*> -> ResultChecker.getErrorMessageIfAvailable(result = this)
я бы еще отказался от экстеншнов, зачем они здесь? почему не обычный метод?

особенно, если это extenstion на Any

2023-07-19 11:01 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/network/MultiNetworkProvider.kt
> +            is Result<*> -> ResultChecker.isNetworkError(result = this)
нельзя, не будет каста, и там разные методы вызываются

2023-07-19 11:25 UTC, roman-pv commented
> Общий вопрос, у нас ни одного провайдера где не используется MultiNetworkProvider? Кажется видел такие

Сейчас не используется там, где по одному провайдеру только. Соответсвенно логировать переключение провайдеров в таком случае не надо.

2023-07-20 07:49 UTC, kozarezvlad approved these changes, later dismissed

2023-07-20 08:01 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/network/CosmosRestProvider.kt
> +class CosmosRestProvider(override val baseUrl: String): NetworkProvider {
internal?

2023-07-20 08:01 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/stellar/StellarNetworkService.kt
> +    override val host: String = stellarMultiProvider.currentProvider.baseUrl
Если я правильно понял, то мы переименовали `host` в `baseUrl`. А почему здесь не переименовалось?

2023-07-20 08:01 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/stellar/StellarWrapperNetworkProvider.kt
> +class StellarWrapperNetworkProvider(
internal

2023-07-20 08:01 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/CycleListIterator.kt
> +class CycleListIterator<E>(private val elements: List<E>) : Iterator<E> {
1. internal
2. Можно ли сделать для гибкости делегат?
`internal class CycleListIterator<E>(elements: Iterator<E>) : Iterator<E> by elements`

2023-07-20 08:01 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/ExceptionHandler.kt
> +    fun handleApiSwitch(currentHost: String, nextHost: String, message: String)
Не уверен на 100%, но если `swith` - это глагол, то будет корректнее назвать `handleApiSwithing`?

2023-07-20 12:41 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/common/ExceptionHandler.kt
> +    fun handleApiSwitch(currentHost: String, nextHost: String, message: String)
копия с iOS, решили лишний раз не трогать, так наверное соглашусь

2023-07-20 12:44 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/stellar/StellarNetworkService.kt
> +    override val host: String = stellarMultiProvider.currentProvider.baseUrl
спасибо, там не унаследовал интерфейс

2023-07-20 12:54 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/common/CycleListIterator.kt
> +class CycleListIterator<E>(private val elements: List<E>) : Iterator<E> {
2 - не очень понял, зачем здесь делегат? И нам нужен доступ к List

2023-07-20 12:56 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/network/CosmosRestProvider.kt
> +class CosmosRestProvider(override val baseUrl: String): NetworkProvider {
не, он там дальше в WalletManager идет

2023-07-20 19:46 UTC, Sateetas approved these changes, later dismissed

2023-07-21 07:10 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/network/CosmosRestProvider.kt
> +class CosmosRestProvider(override val baseUrl: String): NetworkProvider {
`WalletManager` его использует же только в рамках Sdk? Знать приложение о нем не должно

2023-07-21 07:13 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/CycleListIterator.kt
> +class CycleListIterator<E>(private val elements: List<E>) : Iterator<E> {
А как у нас `hasNext` переопределяется? Не увидел реализацию

2023-07-21 07:26 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/common/CycleListIterator.kt
> +class CycleListIterator<E>(private val elements: List<E>) : Iterator<E> {
В этом же файле, в конце класса
`override fun hasNext() = true`
Он же cyclic

2023-07-21 07:27 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/network/CosmosRestProvider.kt
> +class CosmosRestProvider(override val baseUrl: String): NetworkProvider {
Этот тип в конструкторе публичного класса

2023-07-21 07:37 UTC, Mama1emon approved these changes, later dismissed

2023-07-21 11:20 UTC, gbixahue approved these changes

2023-07-21 11:21 UTC, kozarezvlad approved these changes

2023-07-21 11:21 UTC, merged