AND-3815 use only confirmed utxo
tangem/blockchain-sdk-kotlin-old pull request #232
Opened 2023-06-20 12:45 UTC by kozarezvlad

2023-06-20 13:04 UTC, Sateetas requested changes

2023-06-20 13:04 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/network/blockchair/BlockchairNetworkProvider.kt
> +        block: suspend () -> T,
зачем?)
и 20 строками выше аналогично

2023-06-20 13:04 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/network/blockchair/BlockchairNetworkProvider.kt
> +            val unspentOutputs = addressData.unspentOutputs!!
нужно подумать по поводу доменных объектов, чтобы избежать `!!` и `safe call` в куче мест

2023-06-21 03:54 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/network/blockchair/BlockchairNetworkProvider.kt
> +        block: suspend () -> T,
Автоформат

2023-06-21 03:54 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/network/blockchair/BlockchairNetworkProvider.kt
> +            val unspentOutputs = addressData.unspentOutputs!!
Да, в будущем можно подумать, сейчас все ошибки перехватываются в catch и далее в app обработка. В рамках фикса бага не думаю что стоит сейчас делать глобальный рефакторинг моделей в utxo блокчейнах

2023-06-21 05:07 UTC, iiiburnyiii approved these changes

2023-06-22 10:10 UTC, Sateetas approved these changes

2023-06-22 10:12 UTC, merged