AND-3768 Derivation config
tangem/blockchain-sdk-kotlin-old pull request #233
Opened 2023-06-20 17:24 UTC by Sateetas

2023-06-21 08:15 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/CoinTypeProvider.kt
> +        val ethCoinType = 60L
Вродь это поле не нужно

2023-06-21 08:15 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfig.kt
> +abstract class DerivationConfig {
interface?

2023-06-21 08:15 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfigV1.kt
> +/// https://github.com/satoshilabs/slips/blob/master/slip-0044.md
Кажется тут KDoc лучше подойдет. Ещё стоит добавить в доке различия между версиями конфига, а то неочивидно получается

2023-06-21 08:22 UTC, Mama1emon requested changes

2023-06-21 08:22 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/CoinTypeProvider.kt
> +    fun coinType(blockchain: Blockchain, style: DerivationStyle): Long {
Предлагаю именовать функции начиная с глагола. Например, getCoinType

2023-06-21 08:22 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfigV1.kt
> +/// Documentation:
Мб использовать kdoc вместо комментов?

2023-06-21 08:22 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfigV2.kt
> +/// Documentation:
Мб использовать kdoc вместо комментов?

2023-06-21 08:22 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationStyle.kt
> +    fun getConfig() : DerivationConfig {
У нас сейчас есть важность разделять DerivationStyle по версиям?

2023-06-21 08:22 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationStyle.kt
> +    v1,
Предлагаю придерживаться кодстайла котлина. В данном случае, `V1`

2023-06-22 15:05 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/CoinTypeProvider.kt
> +        val ethCoinType = 60L
используется

2023-06-22 15:05 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfig.kt
> +abstract class DerivationConfig {
зачем?

2023-06-22 15:06 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationStyle.kt
> +    fun getConfig() : DerivationConfig {
сейчас нет, это задел на будущее

2023-06-22 15:12 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationStyle.kt
> +    v1,
окей

2023-06-22 15:27 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfigV1.kt
> +/// https://github.com/satoshilabs/slips/blob/master/slip-0044.md
согласен

2023-06-22 15:27 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/CoinTypeProvider.kt
> +    fun coinType(blockchain: Blockchain, style: DerivationStyle): Long {
согласен

2023-06-22 15:27 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfigV1.kt
> +/// Documentation:
согласен

2023-06-22 15:27 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfigV2.kt
> +/// Documentation:
согласен

2023-06-23 10:42 UTC, Mama1emon approved these changes

2023-06-26 11:17 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfig.kt
> +abstract class DerivationConfig {
Абстрактный класс тут избыточен, внутри один абстрактный метод без базовой имплементации

2023-06-26 11:21 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfig.kt
> +abstract class DerivationConfig {
здесь ни при чем методы с имплементациями или без,

абстрактный класс это отношение "является", интерфейс — "имеет качество"

`DerivationConfig` есть суть `DerivationConfigV1` или `DerivationConfigV2` , а не его качество

2023-06-26 11:26 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfig.kt
> +abstract class DerivationConfig {
Не думал с об этом с этой стороны, будем знать

2023-06-26 11:26 UTC, iiiburnyiii approved these changes

2023-06-26 14:35 UTC, merged