AND-3668 Created interface for providing transaction history
tangem/blockchain-sdk-kotlin-old pull request #243
Opened 2023-06-28 11:14 UTC by Yoggam1

2023-06-28 13:04 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryItem.kt
> +    val status: TransactionStatus,
в статус предполагается только подтверждена или нет?
тогда еще нужно поле "тип транзакции", которое будет реализовывать каждый блокчейн

2023-06-28 14:48 UTC, iiiburnyiii requested changes

2023-06-28 14:48 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +object NotImplementedTxHistoryProvider : TransactionHistoryProvider {
Это потом выпилиться? Если да, то надо бы TODO добавить, если нет, то не стоит использовать сокращения.
nit: по неймингу, кажется Dummy или Mock тут лучше подходит

2023-06-28 14:48 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +        Result.Success(TransactionHistoryState.NotImplemented)
По идее должен быть Result.Failure(...). Странно, что NotImplemented считается успешным выполнением операции.

2023-06-28 15:14 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +object NotImplementedTxHistoryProvider : TransactionHistoryProvider {
Это дефолтный провайдер, который будет использоваться во всех блокчейнах, если блокчейн не переопределить его и имплементить фичу историю транзакций

2023-06-28 15:15 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +        Result.Success(TransactionHistoryState.NotImplemented)
Запрос выполнился успешно, но пока блокчейн не поддерживает такую функциональность. Как по мне не поддерживается != ошибке. Под Failure я понимаю ошибку

2023-06-28 15:18 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryItem.kt
> +    val status: TransactionStatus,
Да, под статусом имеется ввиду подтверждена или нет. И сейчас мне не совсем понятно, что за сущность должна быть "тип транзакции" и какие разновидности должны существовать

2023-06-28 15:19 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +object NotImplementedTxHistoryProvider : TransactionHistoryProvider {
Мне тоже не нравиться такой нейминг. Что скажешь по поводу `DefaultTxHistoryProvider`?

2023-06-28 18:53 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryItem.kt
> +    val status: TransactionStatus,
Добавил `TransactionType`. Пока что только с подтипом `Transfer`

2023-06-29 06:13 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +object NotImplementedTxHistoryProvider : TransactionHistoryProvider {
Может есть вариант не использовать провайдер в таких блокчейнах? Кажется это вводит в заблеждение, когда у тебя есть методы для получение истории, но они не отдают данные

2023-06-29 06:14 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +        Result.Success(TransactionHistoryState.NotImplemented)
Так это и есть ошибка же) Это стостояние не относиться к состоянию истории транзакций напрямую

2023-06-29 06:34 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +object NotImplementedTxHistoryProvider : TransactionHistoryProvider {
Изначально так и было, но такой вариант не будет скейлиться и усложнить работу "клиентов". К тому же в клиентах надо реагировать на дефолтное состояние и отрисовывать подходящую вьюшку.

2023-06-29 10:48 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +object NotImplementedTxHistoryProvider : TransactionHistoryProvider {
> Это дефолтный провайдер, который будет использоваться во всех блокчейнах, если блокчейн не переопределить его и имплементить фичу историю транзакций

а если блокчейн не поддерживает 

> Это дефолтный провайдер, который будет использоваться во всех блокчейнах, если блокчейн не переопределить его и имплементить фичу историю транзакций

а зачем?
если история не нужна, просто не имплементи этот интерфейс

2023-06-29 10:49 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryState.kt
> +    object NotImplemented : TransactionHistoryState
лишнее, у нас в принципе не должно быть стейта "not implemented"

2023-06-29 10:51 UTC, Sateetas requested changes
плюс еще ветка не по неймингу названа

2023-06-29 12:08 UTC, ddk9499 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +object NotImplementedTxHistoryProvider : TransactionHistoryProvider {
@Sateetas Посмотри #244, мне кажется вопрос зачем отпадет. WalletManager и его сабклассы не имплементируют интерфейс, а делегируют в отдельную сущность. Это будет либо дефолтный провайдер или реализация(если будет переопределение)

2023-06-29 12:12 UTC, ddk9499 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryState.kt
> +    object NotImplemented : TransactionHistoryState
А как оповещать клиентов, что эта фича не поддерживается в конкретном блокчейне/сети? Может нейминг неудачный(`NotSupported` может больше подходит), но такой стейт нам нужен в приложении.

2023-06-29 12:15 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +object NotImplementedTxHistoryProvider : TransactionHistoryProvider {
@Sateetas Посмотри https://github.com/tangem/blockchain-sdk-kotlin/pull/244, и вопрос зачем отпадет, скорее всего. WalletManager и его сабклассы не имплементируют интерфейс, а делегируют в отдельную сущность. Это будет либо дефолтный провайдер или реализация(если будет переопределено)

2023-06-29 12:16 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryState.kt
> +    object NotImplemented : TransactionHistoryState
А как оповещать клиентов, что эта фича не поддерживается в конкретном блокчейне/сети? Может нейминг неудачный(NotSupported может больше подходит), но такой стейт нам нужен в приложении.

2023-06-29 13:34 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +object NotImplementedTxHistoryProvider : TransactionHistoryProvider {
Мне тоже кажется, что раньше было несколько более понятно. 
Может можно поступить несколько по другому и делегировать получении истории транзакций вообще в отдельную сущность, не связанную с wallet manager?
Если нельзя, то, кажется, лучше в поле с ссылкой на этот провайдер просто null передать, это будет более явно

2023-06-29 14:54 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +object NotImplementedTxHistoryProvider : TransactionHistoryProvider {
Го обсудим, я немного другое имел ввиду под делегатом.
Основная цель была разгрузить WalletManager от лишнего кода. 
Условно есть интерфейс TransactionHistoryProvider, есть EthereumWalletManager и есть TronWalletManager.
Для эфира делаем реализацию, для трона пока нет -> EthereumWalletManager : TransactionHistoryProvider и реализует эти методы интерфейса, но для разгрузки самого менеджера, логика не в нем пишется, а передается в делегат, который логику для эфира истории описывает

2023-06-29 14:55 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +object NotImplementedTxHistoryProvider : TransactionHistoryProvider {
ага, отпишусь в том ревью

2023-06-30 07:18 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryState.kt
> +    object NotImplemented : TransactionHistoryState
а как мы вообще на экран транзакции зайдем в таком случае?

в вариантах "непустой", "пустой", "ошибка", "не может существовать" четвертый явно лишний, его надо на другом уровне обратывать

2023-07-03 07:21 UTC, Mama1emon requested changes

2023-07-03 07:21 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryItem.kt
> +        data class Incoming(val from: String) : TransactionDirection
Под `from` и `to` и предполагается `address`?

2023-07-03 07:21 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +    suspend fun getTransactionHistoryState(walletAddress: String): Result<TransactionHistoryState>
На мой взгляд - аргумент можно сократить до `address`

2023-07-03 07:21 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +object DefaultTxHistoryProvider : TransactionHistoryProvider {
1) Предлагаю вынести в отдельный класс
2) internal?

2023-07-03 07:21 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryState.kt
> +    data class HasTransactions(val txCount: Int) : TransactionHistoryState
`Filled` или `Full`? Что дуамешь?

2023-07-03 07:21 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/binance/BinanceWalletManager.kt
> +) : WalletManager(wallet, presetTokens), TransactionSender, TransactionHistoryProvider by DefaultTxHistoryProvider {
Круто, что используется делегат!
Но есть сомнения касательно использования его, как объекта. Я вижу в этом нарушение принципа `D` из `SOLID`. Создается жесткая привязка и при необходимости подменить реализацию - мы не сможем это сделать.

2023-07-03 08:12 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryState.kt
> +    data class HasTransactions(val txCount: Int) : TransactionHistoryState
`Filled` и `Full` не подходят по значению. Нам надо сообщить что есть транзакции и их число.

Один означает заполнено, а второй полный

2023-07-03 08:13 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryItem.kt
> +        data class Incoming(val from: String) : TransactionDirection
Да

2023-07-03 08:16 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/binance/BinanceWalletManager.kt
> +) : WalletManager(wallet, presetTokens), TransactionSender, TransactionHistoryProvider by DefaultTxHistoryProvider {
Это сделано для тех блокчейнов, у которых пока не имплементировано история транзакций. А для тех блокчейнов который уже есть, в конструктор будет передаваться объект `TransactionHistoryProvider` и его можно будет подменять.

2023-07-03 08:42 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +        Result.Success(TransactionHistoryState.NotImplemented)
Договаривались же, что здесь будет либо null, либо ошибка

2023-07-03 08:48 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +        Result.Success(TransactionHistoryState.NotImplemented)
Обсудили потом еще раз, что сделаем более типизировано и безопасно, чтобы явно было понятно и не приходилось хендлить.
Типа NotImplemented считается успехом, посколько ошибки как таковой нет, просто ЕЩЕ не реализовано для данной сети. А вот когда реализовано мб ошибка апи и тп, что ловится в Failure

2023-07-03 08:50 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryState.kt
> +    object NotImplemented : TransactionHistoryState
@Sateetas Экран деталей токена открывается в любом случае, далее в зависимости от Имплементировано/Не имплементировано в той или иной сети покажем тот или иной UI. Также если Имплементировано, но кинуло ошибку - будет еще другой UI

2023-07-03 09:08 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +object DefaultTxHistoryProvider : TransactionHistoryProvider {
Сделал

2023-07-03 09:09 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +    suspend fun getTransactionHistoryState(walletAddress: String): Result<TransactionHistoryState>
Сделал

2023-07-03 09:11 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/binance/BinanceWalletManager.kt
> +) : WalletManager(wallet, presetTokens), TransactionSender, TransactionHistoryProvider by DefaultTxHistoryProvider {
а обязательно у абстрактного указывать by? нельзя просто интерфейс оставить

2023-07-03 09:22 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/binance/BinanceWalletManager.kt
> +) : WalletManager(wallet, presetTokens), TransactionSender, TransactionHistoryProvider by DefaultTxHistoryProvider {
у всех блокчейнов ты ведь явно проставил делегат, тут по идее можно тогда на него не завязываться и оставить лишь TransactionHistoryProvider

2023-07-03 09:23 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/binance/BinanceWalletManager.kt
> +) : WalletManager(wallet, presetTokens), TransactionSender, TransactionHistoryProvider by DefaultTxHistoryProvider {
Сорри, не сюда написал

2023-07-03 09:23 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/DefaultTxHistoryProvider.kt
> +        Result.Success(TransactionHistoryState.NotImplemented)
а нам точно стоит в обоих методах этого класса возвращать success?

2023-07-03 09:24 UTC, kozarezvlad submitted a review, later dismissed

2023-07-03 09:25 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/DefaultTxHistoryProvider.kt
> +        Result.Success(TransactionHistoryState.NotImplemented)
по идее да, посльку NotImplemented это успех, но просто не реализовано, а вот в Failure полетят ошибки запросов и тп

2023-07-03 09:25 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/DefaultTxHistoryProvider.kt
> +        Result.Success(TransactionHistoryState.NotImplemented)
Да точно. Запрос выполнылся успешно и отдает результать.

2023-07-03 09:26 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/DefaultTxHistoryProvider.kt
> +        Result.Success(TransactionHistoryState.NotImplemented)
можно конечно запихать его и в Failure, но будет больше разбора стейта на обработке реальных ошибок

2023-07-03 09:26 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryItem.kt
> +        data class Incoming(val from: String) : TransactionDirection
Может быть тогда и назвать их `address`? По названию `Incoming` и `Outcoming` что это от кого-то и к кому-то, соответственно.

2023-07-04 05:45 UTC, Mama1emon approved these changes

2023-07-04 06:12 UTC, kozarezvlad approved these changes

2023-07-04 07:10 UTC, Sateetas approved these changes

2023-07-04 07:10 UTC, iiiburnyiii approved these changes

2023-07-04 07:10 UTC, merged

2023-07-04 07:12 UTC, iiiburnyiii approved these changes