AND-3672 Implemented tx history for BTC
tangem/blockchain-sdk-kotlin-old pull request #244
Opened 2023-06-28 19:18 UTC by Yoggam1

2023-06-29 10:38 UTC, Sateetas commented
branch naming should start with `feature/XXX`
https://www.notion.so/tangem/Branches-naming-d632ac63418c47aeb3597434e083a5c6?pvs=4

2023-06-29 10:41 UTC, Sateetas requested changes

2023-06-29 10:41 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +                val isIncoming = tx.vin.any { !it.addresses.contains(walletAddress) }
i would move convertation logic to another entity

2023-06-29 10:41 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/network/blockbook/network/responses/GetAddressResponse.kt
> -        data class Vin(val addresses: List<String>)
i would add moshi annotations everywhere on json fields

simple renaming this property can shoot our legs

2023-06-29 10:41 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/network/blockbook/network/BlockBookApi.kt
> +    suspend fun getTransactions(address: String, page: Int, pageSize: Int): List<GetAddressResponse.Transaction>? {
maybe make return type non-nullable?

2023-06-29 12:25 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/network/blockbook/network/BlockBookApi.kt
> +    suspend fun getTransactions(address: String, page: Int, pageSize: Int): List<GetAddressResponse.Transaction>? {
АПИшка может возвращать null. Не вижу смысла тут менять это. А тот кто вызывает этот метод, в зависимости от своих нужд отработает этот null.

2023-06-29 12:58 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +                val isIncoming = tx.vin.any { !it.addresses.contains(walletAddress) }
Не вижу в этом никакой полезной нагрузки. Была бы какая-то логика как в случае `extractAmount` или `extractTransactionDirection` вынес бы.

2023-06-29 13:16 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/network/blockbook/network/responses/GetAddressResponse.kt
> -        data class Vin(val addresses: List<String>)
Добавил

2023-06-29 15:16 UTC, Sateetas requested changes

2023-06-29 15:16 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +
а зачем так сделано?

это ведь не отображает реальность — у нас не любой wallet manager должен является провайдером истории

2023-06-29 15:16 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/network/blockbook/network/BlockBookApi.kt
> +    suspend fun getTransactions(address: String, page: Int, pageSize: Int): List<GetAddressResponse.Transaction>? {
в идеале бы в эксепшн обернуть, ну да ладно, тут не особо принципиально

2023-06-29 15:16 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProviderExt.kt
> +        else -> DefaultTxHistoryProvider
нужно перечислять все оставшиеся блокчейны (актуально, если решим оставлять использование TransactionHistoryProvider в том виде, в котором оно есть сейчас)

тогда при добавлении нового мы сразу получим compilation error, а в случае с else ошибка проглотится и будет рантаймовой

чем четче контракт, тем меньше проблем в будущем

2023-06-29 15:34 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +
У нас любой walletManager является провайдером истории транзакции, так как у класса `WalletManager` есть функции `getTransactionHistory...` методы

2023-06-30 07:16 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +
в нынешней реализации да, но по сути условный SolanaWalletManager, не имеющий возможности получить историю транзакций, не должен имплементировать `TransactionHistoryProvider`

2023-07-05 06:31 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +                "".hexToBigDecimal()
Это лишнее?

2023-07-05 06:31 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +        } ?: "empty address"
```suggestion
        val v = if (incoming) tx.vin else tx.vout
        val address = v.find { walletAddress !in it.addresses}
            ?.addresses
            ?.firstOrNull()
            ?: EMPTY_ADDRESS
```

2023-07-05 06:31 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProviderExt.kt
> +        else -> DefaultTxHistoryProvider
Плюсую

2023-07-05 06:31 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinWalletManager.kt
> +) : WalletManager(wallet, txHistoryProvider = txHistoryProvider), TransactionSender, SignatureCountValidator {
nit: тут имя параметра можно убрать

2023-07-05 06:47 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinWalletManager.kt
> +) : WalletManager(wallet, txHistoryProvider = txHistoryProvider), TransactionSender, SignatureCountValidator {
Можно конечно. Но как по мне, явное указание лучше. И ничем не грозить

2023-07-05 06:48 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +        } ?: "empty address"
не получиться. У vin и vout разные типы

2023-07-05 06:49 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +                "".hexToBigDecimal()
Удалил

2023-07-05 06:55 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinWalletManager.kt
> +) : WalletManager(wallet, txHistoryProvider = txHistoryProvider), TransactionSender, SignatureCountValidator {
Имхо, но если название параметра и имя переменной совпадает, то это наоборот мешает. За исключением случая когда все параметры именованные. Но это на твое усмотрение

2023-07-05 06:56 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +        } ?: "empty address"
😢
Тогда стоит строку в константу вынести

2023-07-05 06:58 UTC, Mama1emon requested changes

2023-07-05 06:58 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +            if (addressResponse.txs > 0) TransactionHistoryState.Success.HasTransactions(addressResponse.txs)
По кодстайлу проекта - если в одну строчку не умещается, то ставим фигурные скобки

2023-07-05 06:58 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +        } catch (e: Exception) {
Предлагаю добавить логирование

2023-07-05 06:58 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +            val txs = transactions?.map { tx -> tx.toTransactionHistoryItem(walletAddress) }
Не совсем понял. Получается список транзакций может вовсе не прийти в JSON?

2023-07-05 06:58 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +            tx.vin.find { !it.addresses.contains(walletAddress) }?.addresses?.first()
А что гарантирует что инпуты обязательно будут?

2023-07-05 06:58 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +        return if (incoming) TransactionDirection.Incoming(from = address) else TransactionDirection.Outgoing(to = address)
`isIncoming`?

2023-07-05 07:04 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProviderExt.kt
> +internal fun Blockchain.getBitcoinTxHistoryProvider(
а почему этот метод называется `getBitcoinTxHistoryProvider`?

как будем расширять это, когда появятся другие history provider'ы?

2023-07-05 07:06 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProviderExt.kt
> +internal fun Blockchain.getBitcoinTxHistoryProvider(
Предлагаю не использовать сокращения в коде. Сейчас у нас где-то `Tx` где-то `Transactions`, не удобно получается

2023-07-05 07:32 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProviderExt.kt
> +internal fun Blockchain.getBitcoinTxHistoryProvider(
Посмотри пожалуйста как используется `getBitcoinNetworkProviders` это что-то похожее. Если появяться другие провайдеры, которые не касаются битка, то их можно создавть прям на месте или же создать такую экстеншен функцию(для эфира например).

Будь Blockchain sealed то можно было бы написать эту функцию внутри конкретной реализации.

2023-07-05 07:39 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProviderExt.kt
> +internal fun Blockchain.getBitcoinTxHistoryProvider(
Сделал

2023-07-05 07:40 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +            val txs = transactions?.map { tx -> tx.toTransactionHistoryItem(walletAddress) }
На уровне data слоя используется уже готовая DTO, которая переиспользуется. Не стал трогать ее. Поэтому она нуллабельная. И да, она может быть нуллабельной.

2023-07-05 07:41 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +            if (addressResponse.txs > 0) TransactionHistoryState.Success.HasTransactions(addressResponse.txs)
done

2023-07-05 07:43 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +        } catch (e: Exception) {
done

2023-07-05 07:43 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +            tx.vin.find { !it.addresses.contains(walletAddress) }?.addresses?.first()
контракт

2023-07-05 07:44 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +        return if (incoming) TransactionDirection.Incoming(from = address) else TransactionDirection.Outgoing(to = address)
done

2023-07-05 07:45 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +        } ?: "empty address"
сделал

2023-07-05 13:34 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTransactionHistoryProvider.kt
> +        } catch (e: Exception) {
Предлагаю тут хендлить отдельно эксепшен сети, поскольку текущая схема определения наличия сети работает не у всех юзеров и решили вернуться с реактивной схемы, а показ отсутствия сети по факту запроса

2023-07-06 04:35 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTransactionHistoryProvider.kt
> +        } catch (e: Exception) {
1. Что делать с этим эксепшеном?
2. Каждый раз ловить ошибку сети, в каждом месте где идет запрос в сеть?

2023-07-06 07:04 UTC, Sateetas approved these changes, later dismissed

2023-07-06 07:33 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +            tx.vin.find { !it.addresses.contains(walletAddress) }?.addresses?.first()
ты имеешь ввиду, что с сервера не может прийти пустой массив?

2023-07-06 07:41 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTransactionHistoryProvider.kt
> +        } catch (e: Exception) {
Да, в момент запроса если эксепшен связанный с проблемой сети, то писать что нет интернета. Но вроде не много мест где запросы эти идут, около 3-4

2023-07-06 08:32 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTxHistoryProvider.kt
> +            tx.vin.find { !it.addresses.contains(walletAddress) }?.addresses?.first()
Да. В случае битка без vin vout, транзакция не может сущестьвовать.

2023-07-06 12:11 UTC, Mama1emon approved these changes

2023-07-06 12:54 UTC, kozarezvlad approved these changes

2023-07-06 15:19 UTC, merged