AND-3856 AddressService refactoring
tangem/blockchain-sdk-kotlin-old pull request #249
Opened 2023-07-03 11:38 UTC by Sateetas

2023-07-04 05:43 UTC, Mama1emon requested changes

2023-07-04 05:43 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/address/TrustWalletAddressService.kt
> +    blockchain: Blockchain
На мой взгляд - можно в одну строчку. Дело вкуса

2023-07-04 05:43 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressService.kt
> +    fun makeAddress(walletPublicKey: ByteArray, curve: EllipticCurve? = EllipticCurve.Secp256k1): String
Стоит пометить аннотацией `Deprecated`

2023-07-04 05:43 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressService.kt
> +    override fun makeAddress(publicKey: Wallet.PublicKey, addressType: AddressType): AddressPublicKeyPair {
Может быть `create`? make имеет слишком широкое значение

2023-07-04 05:43 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressService.kt
> +        //TODO() check publicKey.blockchainKey
Это в другом МР будет?

2023-07-04 05:43 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressService.kt
> +    // remove "newStyle" later
Задача есть? Может быть сразу здесь указать туду с ссылкой на задачу?

2023-07-04 05:43 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressService.kt
> +interface AddressProvider {
Предлагаю вынести в отдельный файл

2023-07-04 05:43 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressPublicKeyPair.kt
> +data class AddressPublicKeyPair(
Смущает суффикс `Pair` в названии. Что и к чему является парой?

2023-07-04 05:43 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/Wallet.kt
> +        val derivedKey: ByteArray?, // вынести в derivation
?

2023-07-04 05:43 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinAddressService.kt
> +) : MultisigAddressProvider, MultipleAddressProvider {
`Multisig(n)AddressProvider`? Букву пропустили?

2023-07-05 06:50 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressService.kt
> +    fun makeAddress(walletPublicKey: ByteArray, curve: EllipticCurve? = EllipticCurve.Secp256k1): String
Old style имеется ввиду легаси адрес? Тогда Deprecated некорректно будет

2023-07-10 18:25 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/Wallet.kt
> +        val derivedKey: ByteArray?, // вынести в derivation
готово в следующей таске, 

https://github.com/tangem/blockchain-sdk-kotlin/pull/261

2023-07-10 18:26 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressPublicKeyPair.kt
> +data class AddressPublicKeyPair(
address и public key :)

2023-07-10 18:26 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressService.kt
> +interface AddressProvider {
годно

2023-07-10 18:27 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressService.kt
> +        //TODO() check publicKey.blockchainKey
да

2023-07-10 18:28 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressService.kt
> +    override fun makeAddress(publicKey: Wallet.PublicKey, addressType: AddressType): AddressPublicKeyPair {
я предлагаю пока что не сильно уделять внимание неймингу, а в самом конце рефакторинга сесть с айосом и обсудить переименование сущностей 

если буду это делать сейчас, не очень удобно будет рефачить вслед за ними

2023-07-10 18:29 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressService.kt
> +    fun makeAddress(walletPublicKey: ByteArray, curve: EllipticCurve? = EllipticCurve.Secp256k1): String
не, имеется ввида старый стиль выдачи адреса, в противовес `makeAddressNewStyle`

2023-07-10 18:30 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/address/TrustWalletAddressService.kt
> +    blockchain: Blockchain
да, вполне

2023-07-10 18:31 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinAddressService.kt
> +) : MultisigAddressProvider, MultipleAddressProvider {
аналогично с https://github.com/tangem/blockchain-sdk-kotlin/pull/249#discussion_r1258686143

2023-07-10 18:35 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressService.kt
> +    // remove "newStyle" later
ага, [AND-3857](https://tangem.atlassian.net/browse/AND-3857)

я в шапке класса написал коммент

2023-07-10 18:37 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/Wallet.kt
> +        val derivedKey: ByteArray?, // вынести в derivation
в целом все комменты по этому ревью поправлены в том PR, чтобы было менее больно мержить

2023-07-11 07:28 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinAddressService.kt
> +) : MultisigAddressProvider, MultipleAddressProvider {
уточнил — multisig правильно, это общепринятое название

2023-07-11 08:03 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/Wallet.kt
> +        val derivedKey: ByteArray?, // вынести в derivation
Лучше на английском комменты оставлять

2023-07-11 08:06 UTC, Mama1emon approved these changes, later dismissed

2023-07-12 15:04 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/Wallet.kt
> +        val derivedKey: ByteArray?, // вынести в derivation
офк, но тут не особо важно было, это коммент до следующего коммита

документационные конечно на английском

2023-07-24 09:59 UTC, iiiburnyiii approved these changes

2023-07-24 09:59 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/address/MultipleAddressProvider.kt
> +interface MultipleAddressProvider : AddressService {
Лучше 
```suggestion
interface MultipleAddressesProvider : AddressService {
```

2023-07-24 10:08 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/address/MultipleAddressProvider.kt
> +interface MultipleAddressProvider : AddressService {
это удалено в https://github.com/tangem/blockchain-sdk-kotlin/pull/269

2023-07-24 13:21 UTC, roman-pv approved these changes

2023-07-26 07:19 UTC, closed without merging