AND-3934 up card sdk version
tangem/blockchain-sdk-kotlin-old pull request #253
Opened 2023-07-05 15:15 UTC by kozarezvlad

2023-07-06 07:31 UTC, Mama1emon requested changes

2023-07-06 07:31 UTC, Mama1emon commented on .github/workflows/neutral-build.yml
> +          java-version: '8'
8 или 11?

2023-07-06 07:31 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/tezos/TezosConstants.kt
> +            EllipticCurve.Bls12381G2 -> throw Exception("Bls12381G2 is not supported")
Предлагаю не использовать базовый тип исключения. Либо конкретный, либо `error()`

2023-07-06 14:55 UTC, kozarezvlad commented on .github/workflows/neutral-build.yml
> +          java-version: '8'
тестовый ПР чтоб на CI проверить сборку, пока можно не смотреть

2023-07-10 14:42 UTC, Mama1emon approved these changes

2023-07-10 16:00 UTC, Sateetas approved these changes

2023-07-10 16:00 UTC, merged