AND-3906 Wallet refactoring
tangem/blockchain-sdk-kotlin-old pull request #261
Opened 2023-07-10 18:12 UTC by Sateetas

2023-07-11 08:02 UTC, Mama1emon requested changes

2023-07-11 08:02 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinAddressService.kt
>          else -> throw Exception(
Предлагаю использовать определенной тип ошибки, либо `error`, но не родительский тип

2023-07-11 08:02 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinAddressService.kt
> +    private fun make1of2MultisigAddresses(publicKey1: ByteArray, publicKey2: ByteArray): Set<Address> {
Не используется в аппке?

2023-07-11 08:02 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTransactionBuilder.kt
> +    walletAddresses: Set<com.tangem.blockchain.common.address.Address>
Импорт?

2023-07-11 08:02 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +    internal fun getAddressService(): AddressService {
в аппке не используется?

2023-07-11 08:02 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/DummySigner.kt
> +        seedKey = keyPair.publicKey.toCompressedPublicKey(),
А куда еще один параметр затерялся?

2023-07-11 08:02 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/Wallet.kt
> +        get() = walletAddresses.map { it.value }
Метод референс, но на твое усмотрение

2023-07-11 08:02 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/Wallet.kt
> +    private val defaultAddress = walletAddresses[AddressType.Default]!!
Предлагаю использовать requireNotNull с описанием, почему должен быть not null

2023-07-11 08:02 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletFactory.kt
> +        return Wallet(blockchain, addresses, emptySet())
naming args?

2023-07-11 08:02 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/address/PlainAddress.kt
> +data class PlainAddress(
Уже запутался с этими адрессами... А какой еще тип может быть?

2023-07-13 12:46 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinAddressService.kt
> +    private fun make1of2MultisigAddresses(publicKey1: ByteArray, publicKey2: ByteArray): Set<Address> {
неа

2023-07-13 12:50 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinTransactionBuilder.kt
> +    walletAddresses: Set<com.tangem.blockchain.common.address.Address>
тут коллизия была, сделал 2 named импорта

2023-07-13 12:51 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +    internal fun getAddressService(): AddressService {
неа

2023-07-13 12:52 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/DummySigner.kt
> +        seedKey = keyPair.publicKey.toCompressedPublicKey(),
у нас же теперь `derivedKey` и `derivationPath` объединены в `Derivation`, он-то и `null`

2023-07-13 13:02 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/Wallet.kt
> +        get() = walletAddresses.map { it.value }
не фанат метод референсов, особенно в таких простых ситуациях

2023-07-13 13:04 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/Wallet.kt
> +    private val defaultAddress = walletAddresses[AddressType.Default]!!
ага, годно

2023-07-13 13:04 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/address/PlainAddress.kt
> +data class PlainAddress(
пока вот так

![image](https://github.com/tangem/blockchain-sdk-kotlin/assets/13484957/a78059b4-5bef-41a6-bbb0-a0d22c9665f5)

2023-07-13 13:05 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletFactory.kt
> +        return Wallet(blockchain, addresses, emptySet())
готово

2023-07-13 22:44 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinAddressService.kt
>          else -> throw Exception(
готово

2023-07-14 09:50 UTC, Mama1emon approved these changes

2023-07-14 10:19 UTC, Yoggam1 approved these changes

2023-07-14 12:45 UTC, merged