AND-3857 Refactored address services and wallet creation flow.
tangem/blockchain-sdk-kotlin-old pull request #269
Opened 2023-07-18 11:38 UTC by Sateetas

2023-07-24 14:48 UTC, kozarezvlad requested changes

2023-07-24 14:48 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/binance/BinanceAddressService.kt
> +        val hrp = if (testNet) "tbnb" else "bnb"
Понятно что название какое то либовое, но hrp мб получится обозвать как то?

2023-07-24 14:48 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/address/PlainAddress.kt
>  data class PlainAddress(
Мб стоит дописать доку к PlainAddress и просто Address? сходу не понятно в чем разница

2023-07-24 14:48 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinAddressService.kt
> +    // override fun makeAddresses(walletPublicKey: ByteArray, curve: EllipticCurve?): Set<Address> {
Можно удалить?

2023-07-24 14:48 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoincash/BitcoinCashTransactionBuilder.kt
> +    walletAddresses: List<Address>
Тут не было задумки обезопасить от повторения? Может не стоит лист?

2023-07-24 14:48 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/CardanoAddressService.kt
> +    // override fun makeAddresses(walletPublicKey: ByteArray, curve: EllipticCurve?): Set<Address> {
Нельзя выпилить?

2023-07-24 14:48 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/tron/TronAddressService.kt
> -    override fun makeAddress(walletPublicKey: ByteArray, curve: EllipticCurve?): String {
Так понимаю curve не юзалась?

2023-07-24 14:48 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/xrp/XrpAddressService.kt
> -    override fun makeAddress(walletPublicKey: ByteArray, curve: EllipticCurve?): String {
Тут тоже про курв вопрос

2023-07-24 14:48 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +        if (!curves.contains(EllipticCurve.Secp256k1) && !curves.contains(EllipticCurve.Ed25519)) {
Можно тут поставить пометку добавить BLS чтоб не забыть

2023-07-24 14:48 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/Wallet.kt
> +        get() = walletAddresses.map { it.value }.sortedBy { it.type.priority }
А откуда и зачем сортировка?

2023-07-24 14:48 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +    ): WalletManager? {
предлагаю добавить KD на метод, чтобы явно понимать пользователю когда может быть null, либо избавится от null в пользу исключения мб

2023-07-24 14:48 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressProvider.kt
> +fun AddressProvider.makeAddressOldStyle(
почему расширением?
с реализации не очень понятно чем старый от нового отличается

2023-07-24 14:48 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationStyle.kt
> +    fun provider() : DerivationConfig {
вроде в иос конфиг, не пошел ли рассинхрон?

2023-07-24 14:48 UTC, kozarezvlad commented on blockchain/src/test/java/com/tangem/blockchain/Utils.kt
> +internal fun AddressService.makeAddressWithDefaultType(byteArray: ByteArray) : String {
мб в сервис положить и не размазывать по файлам?

2023-07-24 14:48 UTC, kozarezvlad commented on blockchain/src/test/java/com/tangem/blockchain/Utils.kt
> +internal fun AddressService.makeAddressWithLegacyType(byteArray: ByteArray) : String {
и тут

2023-07-24 16:19 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/address/AddressProvider.kt
> +fun AddressProvider.makeAddressOldStyle(
намеренно сделал расширением, т.к. занести внутрь интерфейса нельзя (мы не можем объявить final-метод в интерфейсе),
просто метод с телом можем, но мы не хотим, чтобы была возможность оверрайдить эту имплементацию в имплементорах этого интерфейса

а экстеншн позволяет этого избежать

старый принимает byteArray,новый — Wallet.PublicKey
посмотрю, можно ли сделать поизящнее, у меня вроде была коллизия нейминговая, чекну,актуально ли это сейчас

2023-07-24 16:21 UTC, Sateetas commented on blockchain/src/test/java/com/tangem/blockchain/Utils.kt
> +internal fun AddressService.makeAddressWithDefaultType(byteArray: ByteArray) : String {
это специально для тестов экстеншн, ему не место внутри AddressService

2023-07-24 16:21 UTC, Sateetas commented on blockchain/src/test/java/com/tangem/blockchain/Utils.kt
> +internal fun AddressService.makeAddressWithLegacyType(byteArray: ByteArray) : String {
это специально для тестов экстеншн, ему не место внутри AddressService

2023-07-24 16:24 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationStyle.kt
> +    fun provider() : DerivationConfig {
все ок, в айос provider

2023-07-24 17:41 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/address/PlainAddress.kt
>  data class PlainAddress(
написал доку в Address, там про все рассказал

2023-07-24 17:41 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/binance/BinanceAddressService.kt
> +        val hrp = if (testNet) "tbnb" else "bnb"
готово

2023-07-24 17:41 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinAddressService.kt
> +    // override fun makeAddresses(walletPublicKey: ByteArray, curve: EllipticCurve?): Set<Address> {
ага

2023-07-24 17:42 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/CardanoAddressService.kt
> +    // override fun makeAddresses(walletPublicKey: ByteArray, curve: EllipticCurve?): Set<Address> {
можно

2023-07-24 18:12 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +    ): WalletManager? {
на nullable-менеджерах много что завязано как в сдк, так и в приложении

я не прочь копнуть, но давай отдельной таской

2023-07-24 21:33 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/tron/TronAddressService.kt
> -    override fun makeAddress(walletPublicKey: ByteArray, curve: EllipticCurve?): String {
неа

2023-07-24 21:38 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/xrp/XrpAddressService.kt
> -    override fun makeAddress(walletPublicKey: ByteArray, curve: EllipticCurve?): String {
и здесь нет

но вообще XRP поддерживает две кривых, разберусь с этим, но позже

я создал задачу на это, оставил ссылку в комментарии

2023-07-24 21:39 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +        if (!curves.contains(EllipticCurve.Secp256k1) && !curves.contains(EllipticCurve.Ed25519)) {
?

2023-07-24 21:39 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/Wallet.kt
> +        get() = walletAddresses.map { it.value }.sortedBy { it.type.priority }
нужно чтобы первым всегда шел дефолтный, а не легаси

2023-07-24 21:42 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/bitcoincash/BitcoinCashTransactionBuilder.kt
> +    walletAddresses: List<Address>
неа, да их-то в конце концов максимум 2 — не затеряешься)

обсуждали с Сергеем, что возможно вообще стоит перепроектировать это все, сделав default address обязательным полем, а legacy address — опциональным

во всяком случае пока других типов не предвидится

2023-07-25 11:07 UTC, roman-pv commented on blockchain/src/test/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinAddressTest.kt
> +        // Truth.assertThat(addresses.size).isEqualTo(expectedSize)
раз явно два делаешь, то закомменченную строку и `expectedSize` удаляешь, да?

2023-07-25 11:10 UTC, roman-pv commented
Неудобно, что изменения из девелопа подтянулись только в ветку feature/AND-3857_map_key_to_address и отображаются как изменения пул-реквеста

2023-07-25 13:00 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +        if (!curves.contains(EllipticCurve.Secp256k1) && !curves.contains(EllipticCurve.Ed25519)) {
Кривую поддерживаемую

2023-07-25 13:01 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +    ): WalletManager? {
Просто он же был не null, поэтому спросил

2023-07-25 14:27 UTC, Sateetas commented on blockchain/src/test/java/com/tangem/blockchain/blockchains/bitcoin/BitcoinAddressTest.kt
> +        // Truth.assertThat(addresses.size).isEqualTo(expectedSize)
ага, готово

2023-07-25 15:06 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManagerFactory.kt
> +    ): WalletManager? {
нет, всегда эти методы возвращали nullable-менеджеры

можешь сравнить с дев старым

2023-07-25 15:08 UTC, Sateetas commented
> Неудобно, что изменения из девелопа подтянулись только в ветку feature/AND-3857_map_key_to_address и отображаются как изменения пул-реквеста

странно, не понятно как так вышло

2023-07-26 06:32 UTC, roman-pv approved these changes

2023-07-26 07:27 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +        if (!curves.contains(EllipticCurve.Secp256k1) && !curves.contains(EllipticCurve.Ed25519)) {
готово

2024-09-25 10:01 UTC, closed without merging