AND-4137 Added cosmos tests.
tangem/blockchain-sdk-kotlin-old pull request #279
Opened 2023-07-31 15:46 UTC by Sateetas

2023-08-01 11:03 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosTransactionBuilder.kt
> +        randomByteString: ByteString
стоит добавить примечание, для чего это нужно, и проверку на длину

2023-08-01 13:03 UTC, Yoggam1 commented on blockchain/src/androidTest/kotlin/CosmosAddressTest.kt
> +import androidx.test.runner.AndroidJUnit4
1. Почему они не в пакете?
2. Предлагаю разделить тесты на папки. Либо по блокчейнам, либо по типу(адрес, транзакции и т.д)

2023-08-01 13:04 UTC, Yoggam1 requested changes

2023-08-01 13:04 UTC, Yoggam1 commented on blockchain/src/androidTest/kotlin/CosmosAddressTest.kt
> +import androidx.test.runner.AndroidJUnit4
1. Почему они не в пакете?
2. Предлагаю разделить тесты на папки. Либо по блокчейнам, либо по типу(адрес, транзакции и т.д)

2023-08-02 09:00 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosTransactionBuilder.kt
> +        randomByteString: ByteString
Ага, я это вообще уберу в следующем PR (там вся эта логика переделана), оказалось, что нужно просто добавить 32 любых байта для того,чтобы добить размер транзакции до нужного

можно просто нулями забить

2023-08-02 09:00 UTC, Sateetas commented on blockchain/src/androidTest/kotlin/CosmosAddressTest.kt
> +import androidx.test.runner.AndroidJUnit4
ага, поправил по обоим пунктам

2023-08-02 09:34 UTC, Mama1emon approved these changes

2023-08-02 16:40 UTC, kozarezvlad approved these changes

2023-08-03 06:43 UTC, roman-pv approved these changes

2023-08-03 07:11 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosTransactionBuilder.kt
> +        randomByteString: ByteString
забил нулями в https://github.com/tangem/blockchain-sdk-kotlin/pull/286

2023-08-03 07:28 UTC, Yoggam1 approved these changes

2023-08-03 07:29 UTC, merged