AND-3834 chia integration
tangem/blockchain-sdk-kotlin-old pull request #283
Opened 2023-08-01 16:03 UTC by dbaturin

2023-08-02 09:33 UTC, Mama1emon commented on blockchain/src/test/java/com/tangem/blockchain/blockchains/chia/ChiaTransactionTest.kt
> +// TODO blst library doesn't work with tests yet
Удалить?

2023-08-02 09:35 UTC, kozarezvlad commented on blockchain/src/test/java/com/tangem/blockchain/blockchains/chia/ChiaTransactionTest.kt
> +// TODO blst library doesn't work with tests yet
не надо, она реально не работает т.к. тянет натив, а для этого надо инструментальные тесты тянуть, как в wallet-core

2023-08-02 12:38 UTC, dbaturin commented on blockchain/src/test/java/com/tangem/blockchain/blockchains/chia/ChiaTransactionTest.kt
> +// TODO blst library doesn't work with tests yet
Суть в том, что время уже на тест потрачено, реальные данные повыдёргивал, вроде должен быть рабочий. Если в дальнейшем есть желание сделать тест на сборку транзакции, то, думаю, будет полезно и удалять не стоит, сэкономит время. Тем более, что это в отдельном файле всё лежит, глаза не мозолит.

Если планов таких нет, то можно и удалить.

2023-08-02 16:42 UTC, kozarezvlad commented on blockchain/build.gradle
> +    implementation "org.chiachat:kbls:1.0.3"
а в рамках этого нельзя апдейтнуть bitcoinj? или там кроме версии много поменяется и потребуется переделка?

2023-08-02 16:46 UTC, kozarezvlad approved these changes, later dismissed

2023-08-03 05:46 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/chia/network/ChiaApi.kt
> +    val amount: Long,
давай для всех пропишем, иначе при случайном ренейме проперти можно поломать

2023-08-03 05:55 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/chia/network/ChiaApi.kt
> +    var solution: String
либо var, либо data class

может в ногу стрельнуть, если например в мапу положим, там коллизии equals/hashcode будут

2023-08-03 05:57 UTC, Sateetas commented on blockchain/src/test/java/com/tangem/blockchain/blockchains/chia/ChiaTransactionTest.kt
> +// TODO blst library doesn't work with tests yet
все норм, инструментальные тесты уже есть в соседней ветке, занесем потом

не нужно удалять

2023-08-03 06:02 UTC, Sateetas requested changes
по неймингу ветки: мы решили использовать гитфлоу нейминг
https://www.notion.so/tangem/Branches-naming-d632ac63418c47aeb3597434e083a5c6?pvs=4

сейчас пересоздавать ветку уже не имеет смысла, но в будущем нужно придерживаться нейминга

2023-08-03 06:56 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/chia/network/ChiaApi.kt
> +    val amount: Long,
Да, мы договорились везде указывать @Json(name = "...")

2023-08-03 16:03 UTC, dbaturin commented on blockchain/build.gradle
> +    implementation "org.chiachat:kbls:1.0.3"
Я попробовал, там несколько моментов в NetworkParameters для всех биткоиноподобных приходилось переделать, но это не проблема. Проблема была в либе для Doge, самая новая версия которой основана на старом bitcoinj, без bech32m ещё. Так что с наскока взять не получилось, решил, что лучше отдельно этим заняться.

2023-08-03 16:18 UTC, dbaturin commented
Апишку поправил, про нейминг ветки не в курсе был, в будущем учту

2023-08-08 15:09 UTC, kozarezvlad approved these changes

2023-08-08 15:11 UTC, Sateetas approved these changes

2023-08-08 18:17 UTC, merged