AND-4139 Moved Cardano transaction build to WalletCore
tangem/blockchain-sdk-kotlin-old pull request #291
Opened 2023-08-06 12:33 UTC by Sateetas

2023-08-07 11:06 UTC, Yoggam1 requested changes

2023-08-07 11:06 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/CardanoTransactionBuilder.kt
> +        val preSigningOutput = wallet.core.jni.proto.TransactionCompiler.PreSigningOutput.parseFrom(preImageHashes)
Нужно вынести в импорт

2023-08-10 07:39 UTC, gbixahue approved these changes, later dismissed

2023-08-10 10:44 UTC, kozarezvlad submitted a review, later dismissed

2023-08-10 10:46 UTC, Yoggam1 submitted a review, later dismissed

2023-08-16 09:55 UTC, kozarezvlad approved these changes

2023-08-16 09:56 UTC, gbixahue approved these changes

2023-08-16 09:57 UTC, merged