AND-5051 Added support for transaction history in ETH like blockchains
tangem/blockchain-sdk-kotlin-old pull request #370
Opened 2023-11-08 07:04 UTC by Yoggam1

2023-11-08 07:59 UTC, roman-pv commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/EthereumTransactionHistoryProviderExt.kt
> +    return when (this) {
Пока для всех Eth-like, которые Blockchain.isEvm() == true, не добавлено, поэтому закрытый список?

2023-11-08 08:05 UTC, kozarezvlad requested changes
Давай подольем после среза 5.2, т.к. не успеют в деве до пятницы протестить истории все

2023-11-09 10:00 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/EthereumTransactionHistoryProviderExt.kt
> +    return when (this) {
Да. Не все блокчейны поддерживаем

2023-11-09 10:02 UTC, iMaks99 approved these changes

2023-11-09 10:08 UTC, kozarezvlad approved these changes

2023-11-09 10:08 UTC, merged