feat: add base network
tangem/blockchain-sdk-kotlin-old pull request #531
Opened 2024-03-20 16:26 UTC by Olyno

# Description

Hi 👋🏻 

A lot of users (me included haha) would love to see Base network. It is one of the most used networks out there, and i'm sure people would be happy to see it in Tangem.

As my previous contribution, don't hesitate to make me any feedback about it!

Also, i'm not sure if you would prefer lower case for the network id. Based on the previous networks, i made it upper case.

2024-03-28 15:51 UTC, kozarezvlad submitted a review, later dismissed

2024-03-29 14:00 UTC, kozarezvlad approved these changes

2024-03-29 14:02 UTC, Yoggam1 submitted a review, later dismissed

2024-03-29 14:03 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/externallinkprovider/ExternalLinkProviderFactory.kt
> +            Blockchain.ZkSyncEra, Blockchain.ZkSyncEraTestnet -> ZkSyncEraExternalLinkProvider(isTestnet)
This is duplicating code from line 72

2024-03-29 14:07 UTC, kozarezvlad requested changes
Run please ./gradlew detekt 
before PR

2024-03-29 14:08 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +    Base("Base", "ETH", "Base"),
use lowercase for "id"

2024-04-02 14:40 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfigV1.kt
> +            Blockchain.Base,
Code duplication, lines 70 and 73

2024-04-02 14:47 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/common/Blockchain.kt
> +            BaseTestnet -> Chain.BaseTestnet.id
You forgot about mainnet, add its chain ID as well

2024-04-03 15:25 UTC, iiiburnyiii approved these changes, later dismissed

2024-04-03 15:30 UTC, iMaks99 approved these changes, later dismissed

2024-04-03 15:42 UTC, dbaturin requested changes

2024-04-03 15:42 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/EthereumJsonRpcProvidersExt.kt
> +            EthereumJsonRpcProvider(baseUrl = "https://base-pokt.nodies.app/"),
Provider list lacks the provider Base suggests to use for Metamask - https://mainnet.base.org/
It should be set as a first one.

https://base-pokt.nodies.app/ on the other side appears to be down on https://chainlist.org/.
It should be removed.

2024-04-03 16:22 UTC, Olyno commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/EthereumJsonRpcProvidersExt.kt
> +            EthereumJsonRpcProvider(baseUrl = "https://base-pokt.nodies.app/"),
I don't use Metamask anymore, but if you have any rpc in mind (outside of mainnet which has been added), feel free to tell me :)

2024-04-03 18:33 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/EthereumJsonRpcProvidersExt.kt
> +            EthereumJsonRpcProvider(baseUrl = "https://base-pokt.nodies.app/"),
Blockchain developers usually offer good PRC endpoint maintained by them for Metamask, since it only has one RPC endpoint at a time. Please put it as the first one, the order matters. =)

2024-04-04 10:25 UTC, iMaks99 approved these changes, later dismissed

2024-04-04 11:28 UTC, dbaturin approved these changes

2024-04-04 11:33 UTC, kozarezvlad approved these changes

2024-04-04 11:36 UTC, Mama1emon approved these changes

2024-04-04 11:36 UTC, merged