AND-6667 [Koinos] NetworkProvider
tangem/blockchain-sdk-kotlin-old pull request #566
Opened 2024-04-08 11:23 UTC by MasterBin

2024-04-08 11:27 UTC, MasterBin commented on blockchain/build.gradle
> +        srcDir 'src/main/java/com/tangem/blockchain/blockchains/koinos/proto'
Кто-нибудь знает как сделать internal сгенерированные wire классы для работы с proto? 
В интернетах не нашел инфу
Сейчас все классы public

2024-04-08 16:46 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +            subCode = 999999,
мб тоже в константу вынести для порядка

2024-04-08 16:47 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/network/KoinosApi.kt
> +                // TODO
предлагаю сразу указывать следующую задачу где это будет делаться

2024-04-08 16:47 UTC, kozarezvlad approved these changes, later dismissed

2024-04-09 07:58 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +            subCode = 999999,
Это subCode, он после кода койноса идет

2024-04-09 09:49 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/network/KoinosApi.kt
> +                // TODO
+

2024-04-09 10:07 UTC, Yoggam1 requested changes

2024-04-09 10:07 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +        code = ERROR_CODE_KOINOS,
Следуя практики эксепшенах, тут тоже хорошо бы сделать `ERROR_CODE_KOINOS + subCode`

2024-04-09 10:07 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +            subCode = 999999,
Это какой-то кривой код. Если учесть что мы суммируем сабкод и код коиноса, то получается какая-то непонятная ошибка.

2024-04-09 10:07 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/network/KoinosApi.kt
> +    private val readContractResponseAdapter by lazy { KoinosMethod_ReadContract_ResponseJsonAdapter(moshi) }
`moshi.adapter(KoinosMethod.ReadContract::class.java)`

ниже тоже надо будет переделать

2024-04-09 10:14 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/network/KoinosApi.kt
> +    private val readContractResponseAdapter by lazy { KoinosMethod_ReadContract_ResponseJsonAdapter(moshi) }
Зачем?

2024-04-09 10:15 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +        code = ERROR_CODE_KOINOS,
Так а как потом понять что это ошибка койноса?

2024-04-09 12:09 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +        code = ERROR_CODE_KOINOS,
По коду понять очень просто. По огромному число понятно какой тип ошибки, а по последним числам, именно какая под ошибка

2024-04-09 12:23 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/network/KoinosApi.kt
> +    private val readContractResponseAdapter by lazy { KoinosMethod_ReadContract_ResponseJsonAdapter(moshi) }
1. В таком подходе используется сгенерированный класс и он не всегда резолвиться.
2. Так у них написано в [доке/ридми](https://github.com/square/moshi). А такой подход который ты еаписал я встретил впервые.

2024-04-09 12:40 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +        code = ERROR_CODE_KOINOS,
Так там код минусовой может прилететь

2024-04-09 12:40 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +        code = ERROR_CODE_KOINOS,
Как и у электрума кстати, поэтому и там и там так сделал

2024-04-09 12:41 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/network/KoinosApi.kt
> +    private val readContractResponseAdapter by lazy { KoinosMethod_ReadContract_ResponseJsonAdapter(moshi) }
Что значит не резолвится? 
В Near и Electrum также реализовано

2024-04-09 13:02 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/network/KoinosApi.kt
> +    private val readContractResponseAdapter by lazy { KoinosMethod_ReadContract_ResponseJsonAdapter(moshi) }
В near как раз таки реализовано как я сказал. Да и даже в самих сгенерированных классах используется так же. К тому же как я уже сказал выше, у них в самой доке написано как получать адаптер. Поэтому давай следовать такому подходу.

2024-04-09 13:13 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/network/KoinosApi.kt
> +    private val readContractResponseAdapter by lazy { KoinosMethod_ReadContract_ResponseJsonAdapter(moshi) }
В следующем пр пофикшу для койноса и электрума

2024-04-09 13:15 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/network/KoinosApi.kt
> +    private val readContractResponseAdapter by lazy { KoinosMethod_ReadContract_ResponseJsonAdapter(moshi) }
Решили исправить в след ПРе

2024-04-09 13:15 UTC, Yoggam1 approved these changes

2024-04-09 13:17 UTC, iMaks99 approved these changes

2024-04-09 15:24 UTC, dbaturin requested changes

2024-04-09 15:24 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/network/KoinosApi.kt
> +    }
У нас уже есть такая же функция retryIO, которая по всему SDK используется. Зачем дублировать один и тот же код везде? Или есть отличия?

Я вижу, что тут завязка на конкретный эксепшн, но это точно нужно? Мы через retryIO сетевые проблемы ретраили, а они одинаковые для всех.

2024-04-09 15:24 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/KoinContractAbi.kt
> +        override val eventName: String = "koinos.contracts.token.transfer_event"
Хорошо бы откомментировать, откуда это всё берётся в этих операциях. 

Я в целом в ABI видел это, кроме eventName. Да и name как-будто только для людей идентификатор. Они и у нас пока не используются . Они точно нужны?

2024-04-09 15:24 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/KoinosProviderBuilder.kt
> +                    provider("https://api.koinosblocks.com/"),
Может стоить добавить бесплатный тир https://koinos.pro/?

2024-04-09 15:50 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/network/KoinosApi.kt
> +    }
Не, тут не будет IOException, тут ошибка внутри ответа. Потому что JSON-RPC

2024-04-09 15:52 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/KoinContractAbi.kt
> +        override val eventName: String = "koinos.contracts.token.transfer_event"
Над классом ссылка на протобаф файл
event_name для результата транзакции и для истории транзакций

2024-04-09 15:55 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/KoinosProviderBuilder.kt
> +                    provider("https://api.koinosblocks.com/"),
Можно, нужно тогда акк зарегать

2024-04-09 15:55 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/KoinosProviderBuilder.kt
> +                    provider("https://api.koinosblocks.com/"),
Без ключа вроде как нельзя использовать

2024-04-09 17:34 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/KoinosProviderBuilder.kt
> +                    provider("https://api.koinosblocks.com/"),
Да, нужен акк, Регина этим заведует, вроде, лучше через неё даже бесплатный, наверное. Вдруг, на платный захотим перейти, если другие будут плохо работать.

2024-04-09 17:36 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/network/KoinosApi.kt
> +    }
Нетворк ошибка будет внутри ответа? Если вайфай отрубился или сервер лёг?

2024-04-09 17:50 UTC, dbaturin approved these changes

2024-04-09 17:51 UTC, merged