AND-6638 Create providers according to the list of provider types (1)
tangem/blockchain-sdk-kotlin-old pull request #572
Opened 2024-04-10 15:24 UTC by Mama1emon

2024-04-10 15:52 UTC, iMaks99 approved these changes

2024-04-10 16:28 UTC, MasterBin requested changes
`OnlyPublicProvidersBuilder` доработать бы

Иногда одного url в `abstract fun createProvider(url: String): T?` недостаточно, как, например, для Koinos, нужно знать isTestnet

мб еще добавить `blockchain : Blockchain` параметр?

Можно конечно прокинуть его в конструктор билдера, но тогда получается такая история

```kotlin
networkService = KoinosNetworkService(
        providers = KoinosProviderBuilder(blockchain.isTestnet()).build(blockchain),
),
```

2024-04-10 16:30 UTC, dbaturin approved these changes

2024-04-10 17:39 UTC, kozarezvlad commented
> `OnlyPublicProvidersBuilder` доработать бы
> 
> Иногда одного url в `abstract fun createProvider(url: String): T?` недостаточно, как, например, для Koinos, нужно знать isTestnet
> 
> мб еще добавить `blockchain : Blockchain` параметр?
> 
> Можно конечно прокинуть его в конструктор билдера, но тогда получается такая история
> 
> ```kotlin
> networkService = KoinosNetworkService(
>         providers = KoinosProviderBuilder(blockchain.isTestnet()).build(blockchain),
> ),
> ```

Там же не один url, метод createProvider итеративно создаст столько сколько передашь в конструкторе с разными урлами, лишь реализация провайдера единая, но апи разные

2024-04-11 08:09 UTC, MasterBin approved these changes

2024-04-11 09:07 UTC, merged