AND-6921 added Joystream blockchain
tangem/blockchain-sdk-kotlin-old pull request #609
Opened 2024-05-03 11:04 UTC by kozarezvlad

2024-05-03 16:18 UTC, dbaturin requested changes

2024-05-03 16:18 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/address/EstimationFeeAddressFactory.kt
> +            -> TODO("ADD")
Не забыть бы добавить.

2024-05-03 16:18 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfigV3.kt
> +                mapOf(AddressType.Default to DerivationPath("m/44'/354'/0'/0'/0'"))
Почему деривация как у Польки? Мы же собирались добавить в SLIP-0044 для них coin type и его использовать.

2024-05-03 20:52 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/address/EstimationFeeAddressFactory.kt
> +            -> TODO("ADD")
Именно поэтому поставил сейчас краш.
Чтобы добавить нужно сгенерить адрес на нашем резервном кошельке, а чтобы сгенерить надо протестить и все с адресами порешить

2024-05-03 20:53 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfigV3.kt
> +                mapOf(AddressType.Default to DerivationPath("m/44'/354'/0'/0'/0'"))
посмотрели что в nova wallet используют польку и поставили его, чтобы быть хоть с кем то совместимыми. Но если slip то можем в slip, давай внесем стандарт

2024-05-06 10:20 UTC, dbaturin approved these changes

2024-05-06 11:10 UTC, Mama1emon approved these changes

2024-05-06 11:20 UTC, Yoggam1 approved these changes

2024-05-06 11:21 UTC, merged