AND-6979 Add cardano transaction validator
tangem/blockchain-sdk-kotlin-old pull request #611
Opened 2024-05-07 04:05 UTC by Mama1emon

2024-05-07 12:05 UTC, iMaks99 approved these changes

2024-05-07 12:45 UTC, Yoggam1 approved these changes

2024-05-07 21:21 UTC, dbaturin requested changes

2024-05-07 21:21 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +        object InsufficientMinAdaValueAmount : Cardano(subCode = 3, customMessage = "Insufficient min-ada-value amount")
В чём разница между этими ошибками из их названия не понятно.

2024-05-07 21:21 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +interface TransactionValidator {
У нас же уже есть функция validateTransaction в WalletManager, которую мы переопределяем для некоторых блокчейнов. В ней, правда, нету адреса назначения, но и тут он не важен, вроде. Может не нужна нам вторая?

2024-05-08 08:42 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +interface TransactionValidator {
Я делал по аналогии с IOS.
Да, сейчас функция из WalletManager есть в легаси части приложения, но TransactionValidator, как целевое решение, все-таки, выглядит лучше. 
1) Он отделяет ответственность валидации в отдельную сущность. Таким образом, `WM` перестает быть "и швец, и жнец, и на дуде игрец".
2) Реализатором валидации становится каждый блокчейн. Таким образом, специфика валидации каждого блокчейна реализуется в полном объеме там, где это реально нужно.
3) Совпадение базовых сущностей на двух платформах.

2024-05-08 08:59 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +        object InsufficientMinAdaValueAmount : Cardano(subCode = 3, customMessage = "Insufficient min-ada-value amount")
Напиши, пожалуйста, что именно вызвало у тебя непонимание.

На мой взгляд, названия получились достаточно информативные и емкие. Но так как все равно возникли вопросы, я решил немного разбавить `custom message`. Посмотри, пожалуйста.

Эти ошибки имеют исключительно служебный характер. Пользователи не увидят их.

2024-05-08 12:59 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +interface TransactionValidator {
1. Ну пока в общем не перестаёт, просто конкретно в этом случае мы делаем новый интерфейc для уже имеющегося функционала и два вызова вместо одного.
2. Всё же какая-то базовая логика для валидации она и уже есть и нужна.

В общем, в целом, направление мысли понятное и верное, но пока, как мне кажется, получается менее разумно, чем было. Проблемы никакие не решаются, а ответственность сущностей размывается. Если в будущем как-то всю валидацию по уму сделать, наверное будет лучше. Если есть понимание, как надо в итоге, то может нужно рефакторинг запланировать?

2024-05-08 13:15 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +        object InsufficientMinAdaValueAmount : Cardano(subCode = 3, customMessage = "Insufficient min-ada-value amount")
Ну смотри, все ошибки, кроме последней следуют простой логике, чего где амаунта не хватает и в каком случае.
InsufficientRemainingBalance - не хватает на сдачу
InsufficientRemainingBalanceToWithdrawTokens  - не хватает на cдачу с учётом токенов (withdraw немного не в кассу, но понятно)
InsufficientSendingAdaAmount - не хватает при отправке

InsufficientMinAdaValueAmount - а вот тут, что куда не хватает не понятно совсем. При этом используется термин minAdaValue, который актуален и для всех остальных 3 случаев. И в текстовке этот термин почему-то тоже только здесь.

2024-05-08 13:30 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +        object InsufficientMinAdaValueAmount : Cardano(subCode = 3, customMessage = "Insufficient min-ada-value amount")
InsufficientSendingAdaAmountTokenTransfer должно быть по логике или что-то вроде того

2024-05-08 13:37 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +        object InsufficientMinAdaValueAmount : Cardano(subCode = 3, customMessage = "Insufficient min-ada-value amount")
`InsufficientMinAdaValueAmount` - это ошибка, при которой не хватает ADA для покрытия min-ada-value. То есть, если в первых двух ошибках, как ты правильно подчеркнул, речь идет о сдаче, то в двух последних речь идет про отправляемые суммы – недостаточно ADA для отправки и недостаточно min-ada-value.

Как тебе вариант `InsufficientSendingMinAdaValueAmount`?

2024-05-08 13:42 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +interface TransactionValidator {
Да, довести до ума точно стоит, так как даже сейчас на методе в `WM` стоит `TODO`. Закинул [задачу](https://tangem.atlassian.net/browse/AND-7032?searchObjectId=31209&searchContainerId=10002&searchContentType=issue&searchSessionId=02a5ed74-46ae-4b50-b5a6-f4f2a900ab96) в беклог.

Сейчас предлагаю оставить как есть и в будущем думать в сторону абстракции `TransactionValidator`.

2024-05-08 15:47 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/Exceptions.kt
> +        object InsufficientMinAdaValueAmount : Cardano(subCode = 3, customMessage = "Insufficient min-ada-value amount")
Договорились, исправил

2024-05-08 15:55 UTC, dbaturin approved these changes

2024-05-09 01:19 UTC, merged