AND-6885 Replaced consensus node with mirror nodes. Consensus node used as fallback
tangem/blockchain-sdk-kotlin-old pull request #612
Opened 2024-05-07 14:02 UTC by Yoggam1

2024-05-07 14:13 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/HederaWalletManager.kt
> +        // return Result.Success("0.0.5298242")
Не нужно?

2024-05-07 21:49 UTC, dbaturin requested changes

2024-05-07 21:49 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/HederaWalletManager.kt
> +        // return Result.Success("0.0.5298242")
Не нужно

2024-05-07 21:49 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/HederaWalletManager.kt
> +    private suspend fun sendTransaction(
Функция send строит транзакцию и отдаёт её и подписывать и отсылать в функцию sendTransaction. Что-то странное то ли разделение ролей, то ли нейминг.

2024-05-07 21:49 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/HederaWalletManager.kt
> +        buildTransaction: HederaBuiltTransaction,
*builtTransaction

2024-05-07 21:49 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/network/HederaNetworkService.kt
> +                    isPending = transaction.status == Status.OK,
Это точно правильный статус для pending? В доке у них тухло, только примеры с SUCCESS

2024-05-07 21:49 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/network/HederaNetworkService.kt
> +    private fun getTransactionInfoFromConsensusNode(transactionId: String): Result<HederaTransactionInfo> {
Этот метод можно использовать только 3 минуты после выполнения транзакции, нам это не помешает?

2024-05-08 07:52 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/HederaWalletManager.kt
> +    private suspend fun sendTransaction(
Это попало из след МРа, где есть токены хедеры. Там чтобы ассоцировать токен, тоже нужно отправить транзакцию, но она приходить из метода аля "associate". 

Там принцип работы одинаковый, и send и associate собирают транзакцию, и вызывают метод sendTransaction чтобы отправить транзакцию в блокчейн.

2024-05-08 07:55 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/network/HederaNetworkService.kt
> +                    isPending = transaction.status == Status.OK,
Все что кроме ОК, это уже обработанная транза. И в iOSе также [сделано](https://github.com/tangem/blockchain-sdk-swift/blob/develop/BlockchainSdk/Blockchains/Hedera/Network/HederaNetworkService.swift#L84-L93).

2024-05-08 07:57 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/network/HederaNetworkService.kt
> +    private fun getTransactionInfoFromConsensusNode(transactionId: String): Result<HederaTransactionInfo> {
Нет. Сюда попадает в случае ошибок миррор ноды, и даже если будет ошибка, он попадет в catch. К тому же у нас каждый N секунд обновляется и скорее всего не попадет в трехминутный интервал.

2024-05-08 08:13 UTC, Yoggam1 commented
Что изменилось форс пушем?

1. Изменения по комментариям.
2. Добавил новую сущность, `HederaTransactionId` которая хранить в себе два варианта айдишников. Один из хедера сдк, и его строковый вариант с модификациями(так как апишка и эксплорер не работают с айдишником из сдк если его не модифицировать)

2024-05-08 08:14 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/HederaWalletManager.kt
> +        // return Result.Success("0.0.5298242")
Удалил

2024-05-08 08:14 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/HederaWalletManager.kt
> +        buildTransaction: HederaBuiltTransaction,
Исправил

2024-05-08 09:08 UTC, Sateetas approved these changes

2024-05-08 09:26 UTC, Mama1emon approved these changes

2024-05-08 09:26 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/extensions/String.kt
> +}
Вроде можно проще – `substringBeforeLast(oldValue) + newValue`

2024-05-08 09:32 UTC, iMaks99 approved these changes

2024-05-08 09:55 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/extensions/String.kt
> +}
Этот код не сработает, так как `newValue` берется из самой строки которая модифицируется.

https://pl.kotl.in/k14L3_BCW

2024-05-08 12:00 UTC, dbaturin approved these changes

2024-05-08 12:00 UTC, merged