AND-7008 Added mechanism to invalidate cache one time for all Hedera accounts
tangem/blockchain-sdk-kotlin-old pull request #613
Opened 2024-05-08 16:34 UTC by Yoggam1

2024-05-08 16:38 UTC, Sateetas approved these changes

2024-05-08 16:40 UTC, MasterBin approved these changes

2024-05-08 16:46 UTC, iMaks99 approved these changes

2024-05-08 17:53 UTC, dbaturin approved these changes

2024-05-09 05:00 UTC, Mama1emon requested changes

2024-05-09 05:00 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/HederaWalletManager.kt
> +        }
nit: в целом для однообразия с веткой `Failure` можно было встроить этот код в ветку `Success`

2024-05-09 05:00 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/network/HederaMirrorRestProvider.kt
> +            if (accountData.accounts.size == 1) {
А если он будет больше единицы? То `Failure`?

2024-05-09 08:36 UTC, ddk9499 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/network/HederaMirrorRestProvider.kt
> +            if (accountData.accounts.size == 1) {
Как раз для этого кейса и расчитан фикс

2024-05-09 09:25 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/HederaWalletManager.kt
> +        }
так не прокатить. В случае `Failure` accountId может быть получен из нашего бэка

2024-05-09 09:26 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/hedera/network/HederaMirrorRestProvider.kt
> +            if (accountData.accounts.size == 1) {
Фикс как раз на это и расчитан, если в ответе больше одной записи или нету записи, нужно кидать ошибку. Другими словами, если в ответе не одна запись, то это ошибка.

2024-05-09 09:33 UTC, Mama1emon approved these changes

2024-05-09 09:34 UTC, merged