AND-6895 Removed zero transactions from TransactionHistory
tangem/blockchain-sdk-kotlin-old pull request #633
Opened 2024-05-26 11:04 UTC by Yoggam1

2024-05-27 08:56 UTC, MasterBin approved these changes, later dismissed

2024-05-27 17:28 UTC, dbaturin requested changes
Была плохо поставлена задача. Нулевые транзакции нужно только для EVM токенов убрать. Для EVM важно показывать нулевые транзакции для коина - обычно с нулём взаимодействия с контрактами.

По не EVM нету сходу информации, в коинах без смарт контрактов нельзя 0 послать, да и о таких атаках не известно, так что лучше не трогать.

2024-05-27 17:28 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +        return amount.value == null || amount.value.signum() == 0
У нас есть extension для BigDecimal - isZero(). Удобно, красиво

2024-05-27 17:28 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/transactionhistory/polygon/PolygonTransactionHistoryProvider.kt
> +                excludeZeroAmount = false,
А почему здесь false, когда выше - true?

2024-05-28 05:31 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/txhistory/TransactionHistoryProvider.kt
> +        return amount.value == null || amount.value.signum() == 0
`isZero()` - идет сравнивает с `BIgDecimal.ZERO`. Поэтому не стал его использовать.

2024-05-28 05:33 UTC, Yoggam1 commented
> Была плохо поставлена задача. Нулевые транзакции нужно только для EVM токенов убрать. Для EVM важно показывать нулевые транзакции для коина - обычно с нулём взаимодействия с контрактами. По не EVM нету сходу информации, в коинах без смарт контрактов нельзя 0 послать, да и о таких атаках не известно, так что лучше не трогать.

Но в задаче и в ЛС Леха четко ответил, что надо убрать все нулевые транзакции. Все делалось исходя от его ответов.

2024-05-28 05:37 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/transactionhistory/polygon/PolygonTransactionHistoryProvider.kt
> +                excludeZeroAmount = false,
Хорошее замечание. флаги поменялись местами. Но в целом, в одном случае нам надо урезать нулевые транзакции, а в другом нет. Поэтому используется такой флаг

2024-05-28 08:14 UTC, MasterBin reviewed
Если у нас будет запрос на страницу из 10 элементов и, допустим, 20 будут нулевые, то мы сделаем 3 запроса на бек, правильно?

2024-05-28 08:18 UTC, Yoggam1 commented
> Если у нас будет запрос на страницу из 10 элементов и, допустим, 20 будут нулевые, то мы сделаем 3 запроса на бек, правильно?

Да так и будет. Даже приукрашу пример, если первые пять транзакций не нулевые и дальнейшие 15 нулевые, то тоже будет 3 запроса. Потому что пагинация покажет 5 элементов и сделает след. запросы сразу, так как на UI не хватает элементов.

Чтобы избежать такого, нам нужен свой бек, который сам будет фильтровать транзакции по нашему запросу.

2024-05-28 11:51 UTC, MasterBin commented
> Да так и будет. Даже приукрашу пример, если первые пять транзакций не нулевые и дальнейшие 15 нулевые, то тоже будет 3 запроса. Потому что пагинация покажет 5 элементов и сделает след. запросы сразу, так как на UI не хватает элементов.
> Чтобы избежать такого, нам нужен свой бек, который сам будет фильтровать транзакции по нашему запросу.

Или фича с переключением режима, кмк надо это подсветить Леше. Не круто будет по сто запросов слать

2024-05-28 14:39 UTC, MasterBin approved these changes

2024-05-28 14:41 UTC, kozarezvlad approved these changes

2024-05-28 15:02 UTC, iMaks99 approved these changes

2024-05-28 15:17 UTC, dbaturin approved these changes

2024-05-28 15:17 UTC, merged