AND-7207 Added ability to send BTC to own address
tangem/blockchain-sdk-kotlin-old pull request #642
Opened 2024-05-30 10:20 UTC by iMaks99

2024-05-30 10:50 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +    open val allowUtxoConsolidation: Boolean = false
не очень нравится, что это лежит в общем WalletManager, т.к. не все его наследники utxo. Мб отдельный интерфейс сделать?
@dbaturin что думаешь?

2024-05-30 10:55 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +    open val allowUtxoConsolidation: Boolean = false
Можно интерфейсом UtxoBlockchain например. Или если значение в рантайме не меняется - поле в классе Blockchain

2024-05-30 10:59 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +    open val allowUtxoConsolidation: Boolean = false
Вообще на уровне blockchain звучит хорошо

2024-05-30 11:28 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +    open val allowUtxoConsolidation: Boolean = false
Не все блокчейны UTXO блокчейны. Но остается вопрос, в других блокчейнах имеет смысл оставлять фичу чтобы себе могли отправить? Если нет, то лучше через интерфейс

2024-05-30 11:51 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +    open val allowUtxoConsolidation: Boolean = false
Пока похоже, что этот флаг проще на блокчейн завязать. Но могу представить, что, если развивать эту тему, и интерфейс для UTXO wallet manager'а может пригодиться, а может даже абстрактный класс с какой общей логикой, например, что бы сразу наделать множетсво транзакций сразу для кампаунда UTXO.

2024-05-30 12:07 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +    open val allowUtxoConsolidation: Boolean = false
Алгоритмы с UTXO всякие тоже можно будет подвязать, мне нравится интерфейс

2024-05-30 12:11 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +    open val allowUtxoConsolidation: Boolean = false
Тогда остановились на интерфейсе для wallet manager? чтобы задел на будущее был, потом можно и в абстрактный класс превратить, если более сложная логика кампаунда будет

2024-05-31 08:07 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +interface UtxoConsolidation
UtxoBlockchain может с полем allowConsolidation?

2024-05-31 09:12 UTC, MasterBin approved these changes

2024-05-31 11:20 UTC, kozarezvlad approved these changes

2024-06-03 08:54 UTC, dbaturin requested changes

2024-06-03 08:54 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/WalletManager.kt
> +interface UtxoBlockchain {
Какое название неудачное. WalletManager - это же не Blockchain. Може UtxoManager или UtxoBlockchainManager лучше?

Коммент тоже намекает, что это относится к блокчейну напрямую.

2024-06-03 09:33 UTC, kozarezvlad approved these changes

2024-06-03 09:35 UTC, dbaturin approved these changes

2024-06-03 09:35 UTC, merged