AND-7437 [Koinos] Signature fix
tangem/blockchain-sdk-kotlin-old pull request #673
Opened 2024-06-24 11:51 UTC by MasterBin

2024-06-24 12:17 UTC, dbaturin requested changes

2024-06-24 12:17 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/AnySignerWrapper.kt
> +                    UnmarshalHelper().unmarshalSignatureTron(signResult.data, data ?: ByteArray(0), publicKey)
В общем WalletCoreSigner unmarshal специально для Tron? Что-то тут не так. Судя по "v = 27 + recId", это старый формат для ETH, ну то есть для EVM без EIP-155. Как минимум, это не про Tron, надо переназвать. unmarshalSignatureEVMLegacy может?

2024-06-24 12:56 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/common/AnySignerWrapper.kt
> +                    UnmarshalHelper().unmarshalSignatureTron(signResult.data, data ?: ByteArray(0), publicKey)
ок

2024-06-24 13:29 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/AnySignerWrapper.kt
> +                    UnmarshalHelper().unmarshalSignatureTron(signResult.data, data ?: ByteArray(0), publicKey)
А в свете того, что нагуглил, может и unmarshalSignatureBTCMessage

2024-06-24 13:29 UTC, dbaturin approved these changes

2024-06-25 09:06 UTC, Yoggam1 approved these changes

2024-06-25 09:07 UTC, kozarezvlad approved these changes

2024-06-25 09:10 UTC, merged