AND-7436 Add support different types of address
tangem/blockchain-sdk-kotlin-old pull request #676
Opened 2024-06-26 14:27 UTC by Mama1emon

2024-06-27 09:01 UTC, iMaks99 approved these changes, later dismissed

2024-06-27 09:46 UTC, iMaks99 submitted a review, later dismissed

2024-06-27 12:07 UTC, dbaturin requested changes

2024-06-27 12:07 UTC, dbaturin commented on blockchain/src/androidTest/kotlin/com/tangem/blockchain/blockchains/cardano/utils/CardanoTransactionValidatorTestFactory.kt
> +                assetName = "41474958",
Зря поменял имя. Это же на самом деле assetNameHex, assetName - это "AGIX". Путает только

2024-06-27 12:07 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/CardanoAddressServiceFacade.kt
> +        const val CONTRACT_ADDRESS_MIN_LENGTH = 56
Тоже проблема с неймингом. Это вообще не мин длина. AssetFingerprint короче. Это, очевидно, POLICY_ID_LENGTH

2024-06-27 12:07 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/CardanoTokenAddressConverter.kt
> +        val hash = address.hexToBytes().calculateBlake2b(digestByteSize = 20)
Получается, что в этот конверт что бы подать PolicyID + assetNameHex нужно сначала в другом месте определить, что это именно они и соеденить их. Вроде не очень хорошо получается. Может сюда ещё nullable assetNameHex подавать и всё тут на месте делать?

2024-06-27 12:07 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/utils/CardanoExt.kt
> +internal fun String.isCardanoAsset(policyId: String, assetName: String): Boolean {
Опять нейминг и из названия не понятно, что мы проверяем, что это именно конкретный ассет. Выглядит, как-будто мы проверяем, что это впринципе ассет. matchesCardanoAsset можно было бы. А если функцию для конвертации нормально сделать, то может эта и вообще лишняя, один конверт и сравнение будет прятать...

2024-06-27 12:07 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/utils/CardanoExt.kt
> +    return this == assetFingerprint || this.startsWith(prefix = policyId)
Зачем мы оставляем легаси сравнение? После || нам вариант не нужен же

2024-06-27 13:33 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/CardanoTokenAddressConverter.kt
> +        val hash = address.hexToBytes().calculateBlake2b(digestByteSize = 20)
Не совсем понял. У нас изначально есть адрес (например, юзер вставил в поле контракт адреса), мы его проверяем – является ли он уже фингерпринтом, если да – то ничего не делаем, иначе конвертим.

2024-06-27 13:36 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/utils/CardanoExt.kt
> +internal fun String.isCardanoAsset(policyId: String, assetName: String): Boolean {
Это функция нужна для упрощения работы с токеном, который **точно** является валидным ассетом. У него есть policyId и assetNameHex, который мы уже сравниваем с контракт адресом

2024-06-27 13:38 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/utils/CardanoExt.kt
> +    return this == assetFingerprint || this.startsWith(prefix = policyId)
В целом, если мы гарантируем, что контракт адрес всегда является fingerprint, то можно не делать лишнюю проверку

2024-06-27 13:53 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/CardanoTokenAddressConverter.kt
> +        val hash = address.hexToBytes().calculateBlake2b(digestByteSize = 20)
Но мы этой функцией не можем конвертить policyID, вот, что смущает. Нужно часть действия по конвертации выполнять вне этой функции

2024-06-27 13:59 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cardano/CardanoTokenAddressConverter.kt
> +        val hash = address.hexToBytes().calculateBlake2b(digestByteSize = 20)
То есть нам в приложении придётся проверять, длину адреса, и, если нужно, приклеивать ему assetNameHex, при добавлении кастом токена, правильно же? Вместо того, что бы всё эта функция делала.

2024-06-28 09:54 UTC, dbaturin approved these changes

2024-06-28 09:58 UTC, kozarezvlad approved these changes

2024-06-28 10:05 UTC, merged