AND-7583 Added custom fee model for kaspa in bsdk
tangem/blockchain-sdk-kotlin-old pull request #688
Opened 2024-07-10 13:44 UTC by iMaks99

2024-07-10 13:47 UTC, MasterBin approved these changes, later dismissed

2024-07-10 14:03 UTC, Yoggam1 submitted a review, later dismissed

2024-07-10 17:32 UTC, dbaturin requested changes

2024-07-10 17:32 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/KaspaTransactionBuilder.kt
> +        val unspentsToSpend = getMinimumRequiredUTXOsToSend(
Так потерялась логика с ошибкой, что нельзя больше `MAX_INPUT_COUNT` utxo потратить. Сейчас получился бы change отрицательный, если бы не хватило 84 самых больших инпутов. А дальше

`if (change < BigDecimal.ZERO) { // unspentsToSpend not enough to cover transaction amount
    val maxAmount = transactionData.amount.value + change
    return Result.Failure(BlockchainSdkError.Kaspa.UtxoAmountError(MAX_INPUT_COUNT, maxAmount))
}`

Собственно, не понятно, зачем вообще менять. Используя максимум UTXO даже для маленьких сумм, мы их компаундим в 1 UTXO со сдачей, что важно для Каспы. Давайте вернём как было.

2024-07-10 17:56 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/KaspaTransactionBuilder.kt
> +        val unspentsToSpend = getMinimumRequiredUTXOsToSend(
Было с расчетом на то, что при выставлении кастомной комиссии ты вводишь цену за utxo и условно знаешь что у тебя 1 покроет твою транзакцию и не понимаешь, зачем тебе платить за 84 и почему считает как будто 84 тратишь.
Но в с учетом того что в каспе комиссии копеечные, возможно роли и не сыграет

2024-07-11 06:49 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/KaspaTransactionBuilder.kt
> +        val unspentsToSpend = getMinimumRequiredUTXOsToSend(
Вернул как было

2024-07-11 10:48 UTC, dbaturin approved these changes

2024-07-11 10:57 UTC, kozarezvlad approved these changes

2024-07-11 11:04 UTC, MasterBin approved these changes

2024-07-11 11:06 UTC, merged