AND-7722 [Staking] Integrated Cosmos staking. BSDK part
tangem/blockchain-sdk-kotlin-old pull request #696
Opened 2024-07-24 12:57 UTC by iMaks99

2024-07-24 12:59 UTC, Mama1emon approved these changes, later dismissed

2024-07-25 19:22 UTC, dbaturin requested changes

2024-07-25 19:22 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosTransactionBuilder.kt
> +    fun buildForSign(accountNumber: Long, sequenceNumber: Long, value: ByteArray): ByteArray {
Совершенно неочевидное название "value". Может "compiledTransaction" или "compiledTransactionBytes"?

2024-07-25 19:22 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/cosmos/CosmosTransactionBuilder.kt
> +    fun buildForSend(value: ByteArray, accountNumber: Long, sequenceNumber: Long, signature: ByteArray): String {
Здесь тоже

2024-07-26 07:18 UTC, Mama1emon approved these changes

2024-07-26 11:17 UTC, Sateetas approved these changes

2024-07-26 18:01 UTC, dbaturin approved these changes

2024-07-29 05:22 UTC, merged