AND-7712 Add Filecoin blockchain
tangem/blockchain-sdk-kotlin-old pull request #697
Opened 2024-07-24 12:57 UTC by Mama1emon

2024-07-24 13:47 UTC, iMaks99 submitted a review, later dismissed

2024-07-24 15:03 UTC, MasterBin submitted a review, later dismissed

2024-07-24 16:26 UTC, Yoggam1 submitted a review, later dismissed

2024-07-25 18:58 UTC, dbaturin requested changes
А не лучше ли незаконченную интеграцию в фича ветку лить? Это нигде не может стрельнуть?

2024-07-25 18:58 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/externallinkprovider/providers/FilecoinExternalLinkProvider.kt
> +    override val explorerBaseUrl = "https://filfox.info/en/"
```suggestion
    override val explorerBaseUrl = "https://filfox.info/"
```

2024-07-25 18:58 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/externallinkprovider/providers/FilecoinExternalLinkProvider.kt
> +    override val explorerBaseUrl = "https://filfox.info/en/"
Не надо язык хардкодить, наверное? Пусть по геолокации определяют, если хотят. Работает, я проверил.

2024-07-28 12:35 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/externallinkprovider/providers/FilecoinExternalLinkProvider.kt
> +    override val explorerBaseUrl = "https://filfox.info/en/"
Согласен, поправил

2024-07-28 12:43 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/externallinkprovider/providers/FilecoinExternalLinkProvider.kt
> +    override val explorerBaseUrl = "https://filfox.info/en/"
Касательно интеграции блокчейна – на данный момент в приложении уже выстроены все необходимые механизмы, чтобы разрабатываемые блокчейны не аффектили на работу. Даже если такой код попадет в релиз.

Что же насчет фича-веток – на мой взгляд, к ним стоит прибегать только в крайнем случае. Например, когда невозможно закрыть фича тогглом. Ограничение на влитие в такие ветки кода никак не ограничено, можно пушить столько, сколько захочешь. А потом при мердже в дев тяжело проводить ревью огромного кол-ва файлов

2024-07-29 09:17 UTC, dbaturin approved these changes

2024-07-29 09:34 UTC, kozarezvlad approved these changes

2024-07-29 09:55 UTC, iMaks99 approved these changes

2024-07-29 09:55 UTC, merged