AND-6769 AND-6914 Fixed sending Mantle max amount.
tangem/blockchain-sdk-kotlin-old pull request #705
Opened 2024-08-01 17:40 UTC by Sateetas

2024-08-01 17:59 UTC, dbaturin requested changes

2024-08-01 17:59 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/mantle/MantleWalletManager.kt
> +                        amount = transactionData.amount.minus(ONE_WEI),
Здесь не надо вычитать этот вей вычитать, только при запросе фи.

2024-08-02 10:26 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/mantle/MantleWalletManager.kt
> +                        amount = transactionData.amount.minus(ONE_WEI),
поправил

2024-08-02 13:37 UTC, kozarezvlad approved these changes

2024-08-02 14:36 UTC, dbaturin approved these changes

2024-08-02 15:36 UTC, iMaks99 approved these changes

2024-08-02 15:36 UTC, merged