AND-7893 [Staking] Added polygon staking to BSDK
tangem/blockchain-sdk-kotlin-old pull request #721
Opened 2024-08-12 07:32 UTC by iMaks99

2024-08-12 08:37 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/decimal/DecimalNetworkService.kt
> +    override suspend fun getAllowance(
nit: мб во всех местах import alias прописать? KotlinResult, например

мест его использования не так много
чуть красивее будет смотреться

2024-08-12 08:43 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/solana/SolanaWalletManager.kt
> +                    value = (byteArrayOf(1) + signResult + transactionWithoutSignaturePlaceholder).toHexString(),
тут никак не получится сделать по-другому?
то есть мы создаем массив байт, перегоняем его в string, и в следующей строчке вызываем `sendTransaction()`, где происходит обратное преобразование

мб подумать в сторону того, чтобы разбить `Compiled` на `Bytes` и `Hex`?
или просто сделать в существующем дополнительные свойства?

2024-08-12 08:53 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/solana/SolanaWalletManager.kt
> +                    value = (byteArrayOf(1) + signResult + transactionWithoutSignaturePlaceholder).toHexString(),
Хм, думаю можно разбить на Bytes и Hex для большей понятности

2024-08-12 11:42 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/decimal/DecimalNetworkService.kt
> +    override suspend fun getAllowance(
В обсуждении убрать все вариации Result, оставив только kotlin, тогда разом решится этот вопрос и не будет нужды в alias

2024-08-12 12:21 UTC, dbaturin requested changes
А почему флоу, используемый для WalletConnect не используем?

2024-08-12 12:21 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/EthereumUtils.kt
> +        val parsed = moshi.adapter(EthereumCompiledTransaction::class.java).fromJson(compiledTransaction) ?: return null
Мы берём хекс и парсим его как JSON? Что-то не то, это же не хекс, значит. Зачем путать?

2024-08-12 12:21 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/decimal/DecimalNetworkService.kt
> +    override suspend fun getAllowance(
Так уже решено переходить на Котлиновский резалт или нет? Не совсем понятно, почему какой-то частичный переход.

2024-08-12 12:34 UTC, iMaks99 commented
Флоу WalletConnect находится на легаси уровне. Более того, логика флоу соответствует логике, которая находится bsdk, скорее будет лучше флоу wallet connect изменить так, чтобы общение было через новые абстракции TransactionData убрав blockсhain-specific логику из апп в bsdk

2024-08-12 12:34 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/EthereumUtils.kt
> +        val parsed = moshi.adapter(EthereumCompiledTransaction::class.java).fromJson(compiledTransaction) ?: return null
Изменил на RawString

2024-08-12 12:36 UTC, iMaks99 commented
Часть новых методов начали писать на kotlin.Result. На месте использования сочел нужным изменить, чтобы избежать путаницы с зависимостями. Задачу на переход еще не делали

2024-08-12 12:45 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/decimal/DecimalNetworkService.kt
> +    override suspend fun getAllowance(
Часть новых методов начали писать на kotlin.Result. На месте использования сочел нужным изменить, чтобы избежать путаницы с зависимостями. Задачу на переход еще не делали

2024-08-12 12:49 UTC, dbaturin submitted a review, later dismissed

2024-08-12 13:04 UTC, Yoggam1 submitted a review, later dismissed

2024-08-12 13:16 UTC, Sateetas submitted a review, later dismissed

2024-08-13 11:18 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/EthereumUtils.kt
> +        val parsed = moshi.adapter(EthereumCompiledTransaction::class.java).fromJson(compiledTransaction) ?: return null
мб не создавать адаптер каждый вызов?

2024-08-13 11:19 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/EthereumUtils.kt
> +        val gasLimit = parsed.gasLimit.hexToBigDecimal().toBigInteger()
возможно стоит сразу добавить тут валидации на 0 и тп, чтобы транзакцию не отправить с кривыми данными и комиссию не сжечь

2024-08-13 11:20 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/tron/network/TronNetworkService.kt
> +    suspend fun getAllowance(ownerAddress: String, token: Token, spenderAddress: String): kotlin.Result<BigDecimal> {
А почему переделано на котлиновский резалт? в приложении хендлится много где именно сдк резалт

2024-08-13 11:20 UTC, kozarezvlad requested changes
пару вопросов

2024-08-13 12:01 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/tron/network/TronNetworkService.kt
> +    suspend fun getAllowance(ownerAddress: String, token: Token, spenderAddress: String): kotlin.Result<BigDecimal> {
Есть несколько разных реализаций Result в сдк (SimpleResult, Result, CompletionResult) выполняющих одно и тоже. Наличие разных реализаций также является причиной путаницы не неконсистентности в ошибках, на одну и ту же ошибку может прийти как wrapped tangem error, так и просто tangem error. @Mama1emon предложил отойти от них в пользу kotlin.Result, который выполняет то же самое, что и наши реализации, но без зависимости на наши модели. Валидация транзакции была реализована через kotlin.Result, что приводит сейчас к проблемам с зависимостями в репозитории в аппке, поэтому точечно тут поменял (в аппке это затрагивает только одно место в свопе)

2024-08-13 12:22 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/tron/network/TronNetworkService.kt
> +    suspend fun getAllowance(ownerAddress: String, token: Token, spenderAddress: String): kotlin.Result<BigDecimal> {
я когда дорабатывал в методе send чтобы возвращало хэш транзакции, приводил все ошибки к нужном типам, по сути есть 2 типа - ошибки блокчейн sdk, ошибки card sdk, вторые могут стрельнуть при подписи картой и как раз они враппятся в WrappedTangemError. Итого получается, что есть BlockchainError который может прилетет, а далее в нем либо по конкретному блокчейну, либо wrapped в которой мы понимаем, что лежит что то из card sdk. Если мы уйдем на котлин резалт, то будет Throwable, как в таком случае при хендилнге будем разделять ошибки сдк карт и блокчейна?

2024-08-13 13:33 UTC, kozarezvlad approved these changes

2024-08-13 13:37 UTC, Sateetas approved these changes

2024-08-13 13:47 UTC, dbaturin approved these changes

2024-08-13 14:41 UTC, merged