AND-7907 tezos fee estimation include allocation
tangem/blockchain-sdk-kotlin-old pull request #722
Opened 2024-08-14 11:15 UTC by kozarezvlad

2024-08-15 07:29 UTC, iMaks99 approved these changes, later dismissed

2024-08-15 14:44 UTC, dbaturin requested changes
На строке 140 учитываем allocation fee как положено

2024-08-19 09:13 UTC, kozarezvlad commented
> На строке 140 учитываем allocation fee как положено

Ты имеешь ввиду что проверяется баланс адреса назначения?

2024-08-19 09:33 UTC, kozarezvlad commented
> На строке 140 учитываем allocation fee как положено

Убрал вообще доп код, сделал вызов через тот же getFee и плюсом убрал прихранивание стейта publicKeyRevealed, в целом плохая практика как показало хранить стейт между вызовами методов walletManager

2024-08-19 11:51 UTC, dbaturin approved these changes

2024-08-19 11:51 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/tezos/TezosWalletManager.kt
> +        return getFee(amount, destination)
Наверно, можно бы уже эту функцию было бы убрать, она просто ссылается на другую, получается...

2024-08-19 11:54 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/tezos/TezosWalletManager.kt
> +        return getFee(amount, destination)
есть estimateFee которая используется для оценки, пользователь вызывает ее и ее реализация зависит от сети к сети. Если ее не использовать, то где то делать проверку что за блокчейн и вызывать либо getFee либо estimateFee, что неверно

2024-08-19 13:12 UTC, iMaks99 approved these changes

2024-08-19 13:13 UTC, Sateetas approved these changes

2024-08-19 13:13 UTC, merged