AND-8064 [Staking] [Solana] Migrated to confirmed commitment
tangem/blockchain-sdk-kotlin-old pull request #736
Opened 2024-08-26 09:20 UTC by iMaks99

Перевел получение blockhash в статусе CONFIRMED. Добавил timeout на переотправку в 18 сек и 3 сек задержкой retry.

```
Provider: quiknode. sendTransaction begins: 120010563
Provider: nownodes. sendTransaction begins: 1200105634
Provider: solana.com. sendTransaction begins: 1200105634
Provider: quiknode. Retry: 1200113308, diff: 7674
Provider: solana.com. Retry: 1200113369, diff: 7735
Provider: nownodes. Retry: 1200113700, diff: 8066
Provider: quiknode. Success: 1200116944, diff: 11310
Provider: nownodes. Success: 1200124153, diff: 18519
``` 

_solana.com_ падает на 2 retry с ошибкой: _Too many requests for a specific RPC call_

2024-08-26 12:42 UTC, Sateetas approved these changes, later dismissed

2024-08-27 14:17 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/solana/SolanaWalletManager.kt
> +                val startSendingTimestamp = SystemClock.elapsedRealtime()
Кмк надо это в TransactionData добавить

2024-08-27 14:17 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/solana/SolanaWalletManager.kt
> +                val startSendingTimestamp = SystemClock.elapsedRealtime()
Если я правильно понял по комменту

2024-08-27 14:20 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/solana/SolanaNetworkService.kt
> +                    return@withContext sendTransaction(signedTransaction, startSendingTimestamp)
nit: лучше без рекурсии

2024-08-28 16:32 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/solana/SolanaNetworkService.kt
> +    private fun Exception.isBlockchainNotFound(): Boolean {
isBlockhashNotFound?

2024-08-29 14:27 UTC, dbaturin requested changes

2024-08-29 14:27 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/solana/SolanaNetworkService.kt
> +        delay(START_DELAY) // Too early to send transaction, waiting for blockhash to generate
Не, так не пойдёт, мы обсуждали, что мы запоминаем время, когда получили блокхэш, и после него должны пройти 15 секунд. В это время пользователь будет подписывать транзакцию, когда до сенда дойдёт, они уже истечь могут. В iOS именно так реализовано

2024-09-02 10:24 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/solana/SolanaNetworkService.kt
> +                delay(WAIT_DELAY)
а можем сделать delay(START_DELAY - elapsedTime) и не дергать рекурсию?

2024-09-02 10:26 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/solana/SolanaNetworkService.kt
> +                    return@withContext sendTransaction(signedTransaction, startSendingTimestamp)
тут по идее если мы проскочим окно и BlockhashNotFound будет уже, то sendTransaction будет дергаться бесконечно долго?

2024-09-02 11:22 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/solana/SolanaNetworkService.kt
> +                    return@withContext sendTransaction(signedTransaction, startSendingTimestamp)
Хороший вопрос, проверю

2024-09-02 12:08 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/solana/SolanaNetworkService.kt
> +                    return@withContext sendTransaction(signedTransaction, startSendingTimestamp)
Добавил лимит в 5 попыток

2024-09-02 12:12 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/solana/SolanaNetworkService.kt
> +            delay(START_DELAY - elapsedTime)
а если получается отрицательное, то delay просто проходит, не упадет?

2024-09-02 12:13 UTC, kozarezvlad approved these changes

2024-09-02 12:14 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/solana/SolanaNetworkService.kt
> +            delay(START_DELAY - elapsedTime)
Не упадет, delay пропустится

2024-09-02 12:15 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/solana/SolanaNetworkService.kt
> +            delay(START_DELAY - elapsedTime)
```
16:23:07.700 Solana          E  Start 105761235
16:23:37.537 Solana          E  Start delay. Diff 14837. solana.com
16:23:37.538 Solana          E  Start delay. Diff 14837. nownodes.io
16:23:37.538 Solana          E  Start delay. Diff 14837. quiknode.pro
16:23:37.539 Solana          E  Try send transaction. nownodes.io
16:23:37.539 Solana          E  Try send transaction. solana.com
16:23:37.539 Solana          E  Try send transaction. quiknode.pro
16:24:02.628 Solana          E  Start 105816163
16:24:06.821 Solana          E  Start delay. Diff -10807. solana.com
16:24:06.822 Solana          E  Start delay. Diff -10807. quiknode.pro
16:24:06.822 Solana          E  Start delay. Diff -10807. nownodes.io
16:24:17.632 Solana          E  Try send transaction. https://api.mainnet-beta.solana.com
16:24:17.632 Solana          E  Try send transaction. https://sol.nownodes.io
16:24:17.633 Solana          E  Try send transaction. https://hidden-greatest-sky.solana-mainnet.discover.quiknode.pro/99328903f6cfe375b91b2b1ee8e8a5ab582dde22
```

2024-09-02 13:38 UTC, dbaturin approved these changes
Чуть-чуть отличается логика от iOS. Там, когда собираем uncompiled транзакцию, время запоминаем именно на запросе блокхэша.

Но я думаю, не принципиально, разница минимальная должна быть.

2024-09-02 14:09 UTC, Mama1emon approved these changes

2024-09-02 14:12 UTC, merged