AND-7676 Add EIP1559 fee calculating in EthereumWalletManager
tangem/blockchain-sdk-kotlin-old pull request #756
Opened 2024-09-11 12:35 UTC by Mama1emon

2024-09-18 08:41 UTC, nzeeei submitted a review, later dismissed

2024-09-18 09:40 UTC, iMaks99 approved these changes, later dismissed

2024-09-19 10:24 UTC, dbaturin requested changes

2024-09-19 10:24 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumLegacyTransactionBuilder.kt
> +            walletPublicKey = decompressedPublicKey.sliceArray(1..PUBLIC_KEY_SIZE),
Почему это поменялось?

Константа ещё неправильно используется. Если она к исходному ключу относится, то она неправду говорит, ведь длина исходного ключа 65 байт. Если к получаемому, то почему мы вообще используем его как верхнюю границу исходного? Ну и, собственно о чём константа непонятно в любом случае, не однозначно.

Может использовать желаемую длину и .takeLast? Ну и назвать однозначнее

2024-09-19 10:24 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTransactionBuilder.kt
> +    protected val decompressedPublicKey by lazy { wallet.publicKey.blockchainKey.toDecompressedPublicKey() }
А здесь почему поменялось?

2024-09-19 10:24 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +            .asRSV()
А здесь почему офсета больше нет?

2024-09-19 10:24 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/UnmarshalHelper.kt
>                      .sliceArray(1..PUBLIC_KEY_SIZE),
Вижу отсюда константа пришла, хотелось бы поправить.

Ну и вообще, почему мы этот ключ обрезаем в двух разных местах теперь, а не в одном?

2024-09-20 09:41 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumLegacyTransactionBuilder.kt
> +            walletPublicKey = decompressedPublicKey.sliceArray(1..PUBLIC_KEY_SIZE),
Здесь все проще. Я когда контракты объединял, то неправильно перенес. Вот так раньше было.
В будущем этот билдер удалю, поэтому нет смысла ничего менять
<img width="903" alt="изображение" src="https://github.com/user-attachments/assets/9fb75d78-b650-4f14-80b1-0673252b3838">

2024-09-20 09:43 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTransactionBuilder.kt
> +    protected val decompressedPublicKey by lazy { wallet.publicKey.blockchainKey.toDecompressedPublicKey() }
Оставил объяснение на прошлом комменте.
Для легаси билдера надо делать slice, для нового не надо

2024-09-20 09:45 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +            .asRSV()
Я сперва сделал на подобии с iOS, а потом понял, что у них это костыль.
WalletCore сам высчитывает значение recId под капотом. Тут не нужен оффсет

2024-09-20 09:46 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/common/UnmarshalHelper.kt
>                      .sliceArray(1..PUBLIC_KEY_SIZE),
См. выше. Там был легаси билдер, который нужно починить для обатной совместимости. Потом я его выпилю

2024-09-20 15:36 UTC, dbaturin approved these changes

2024-09-20 15:40 UTC, iMaks99 approved these changes

2024-09-20 16:46 UTC, kozarezvlad approved these changes

2024-09-21 07:20 UTC, merged