AND-8187 Added support for SUI network
tangem/blockchain-sdk-kotlin-old pull request #771
Opened 2024-09-19 15:39 UTC by iiiburnyiii

2024-09-19 17:17 UTC, nzeeei approved these changes, later dismissed

2024-09-20 05:21 UTC, iMaks99 approved these changes, later dismissed

2024-09-24 14:54 UTC, siblockchaina commented on blockchain/src/main/java/com/tangem/blockchain/common/address/EstimationFeeAddressFactory.kt
> +            -> "0xd185afd5171875605562a1bf7d2216c4bec2fcaea0be7e23cfb80ac5819e4617"
в моей реализации был воткнут мой же тестовый адрес - что неверно, следует убрать или не забыть убрать после генерации необходимого адреса для этого кейса

2024-09-24 16:25 UTC, siblockchaina requested changes

2024-09-24 16:25 UTC, siblockchaina commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfigV3.kt
> +            -> mapOf(AddressType.Default to DerivationPath("m/44'/784'/0'/0/0"))
"m/44'/784'/0'/0'/0'"
все hardened для нашей реализации ed25519

2024-09-24 16:25 UTC, siblockchaina commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/sui/SuiWalletManager.kt
> +        val gasUsed = txResponse.effects.gasUsed
нужно добавить проверку effects.status т.к значения gasBudget могу проходить расчет но итоговый результат будет fail(insufficient gas)

2024-09-24 16:25 UTC, siblockchaina commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/sui/SuiTransactionBuilder.kt
> +        const val MIN_GAS_BUDGET = 1_000_000L // 0.01 SUI
по доке он 1,075,000 MIST, но и при этом dryRun.. выдавал ошибку "to low", считать лучше от максимально возможных значений бюджета

2024-09-24 16:25 UTC, siblockchaina commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/sui/SuiTransactionBuilder.kt
> +                maxOf(MIN_GAS_BUDGET, reducedBalance)
у бюджета есть верхний потолок, превышение приведет к fail

2024-09-24 16:25 UTC, siblockchaina commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/sui/SuiTransactionBuilder.kt
> +        val isPayAll = reducedBalance <= MIN_GAS_BUDGET
точно ли тут нужно сравнивать с MIN_GAS_BUDGET ?

2024-09-24 16:25 UTC, siblockchaina commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/sui/SuiWalletManager.kt
> +            gasBudget = (grossTotalGasMist + gasUsed.computationCost).toLong(),
тестовые транзакции показывали что grossTotalGasMist достаточно (учитывая что из этого еще вычитается Storage Rebate),  поэтому для "+ gasUsed.computationCost" нет необходимости

2024-09-26 07:55 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/sui/SuiTransactionBuilder.kt
> +                maxOf(MIN_GAS_BUDGET, reducedBalance)
В методе получения reducedBalance есть ограничение в 50_000_000 MIST

2024-09-26 07:57 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/sui/SuiTransactionBuilder.kt
> +        const val MIN_GAS_BUDGET = 1_000_000L // 0.01 SUI
По доке там вообще 2_000) Но при нём dry run падает
<img width="848" alt="image" src="https://github.com/user-attachments/assets/c09d1733-9a41-423c-b74b-6e02651b62af">

2024-09-26 08:01 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/sui/SuiTransactionBuilder.kt
> +        val isPayAll = reducedBalance <= MIN_GAS_BUDGET
Больше не нашел вариантов, тут нужно учесть случай когда пользователь выводит баланс почти под ноль и комиссия вычитается из суммы перевода, в этом случае всё равно стоит использовать pay all, так как на балансе у пользователя ничего не остаётся после транзакции

2024-09-26 08:01 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/sui/SuiWalletManager.kt
> +            gasBudget = (grossTotalGasMist + gasUsed.computationCost).toLong(),
Да, достаточно, но официальный кошелёк считает по такой формуле, решил сделать так же

2024-09-26 08:02 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/sui/SuiWalletManager.kt
> +        val gasUsed = txResponse.effects.gasUsed
Что нужно будет сделать если status == fail, вызвать dry run ещё раз?

2024-09-26 09:36 UTC, siblockchaina commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/sui/SuiWalletManager.kt
> +            gasBudget = (grossTotalGasMist + gasUsed.computationCost).toLong(),
я думаю что нужно нам одинаково сделать (под мою ответственность), когда/если что то пойдет не так будем разбираться с основаниями для увеличения комиссии более конкретно (на кой случай там делать х2 computationCost например, почему именно x2 и от чего это может зависеть), сейчас нет оснований

2024-09-26 23:51 UTC, siblockchaina commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/sui/SuiTransactionBuilder.kt
> +        val coins = getCoinsForAmount(walletInfo, amountMist)
тут койны надо собирать на amount + budget, чтоб все покрыло

2024-09-30 14:11 UTC, siblockchaina commented on blockchain/src/main/java/com/tangem/blockchain/common/address/EstimationFeeAddressFactory.kt
> +            -> "0xd185afd5171875605562a1bf7d2216c4bec2fcaea0be7e23cfb80ac5819e4617"
0xbca45e36a271e106546c89984108685215724e488570a0049a187c473cd521bc

2024-10-01 12:32 UTC, siblockchaina approved these changes

2024-10-01 13:59 UTC, kozarezvlad approved these changes

2024-10-01 15:02 UTC, dbaturin approved these changes

2024-10-01 15:02 UTC, merged