AND-8446: Add Energy Web X support
tangem/blockchain-sdk-kotlin-old pull request #773
Opened 2024-09-20 07:52 UTC by nzeeei

2024-09-20 09:05 UTC, kozarezvlad submitted a review, later dismissed

2024-09-20 11:14 UTC, iiiburnyiii approved these changes, later dismissed

2024-09-23 13:15 UTC, dbaturin requested changes

2024-09-23 13:15 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfigV3.kt
> +            -> mapOf(AddressType.Default to DerivationPath("m/44'/246'/0'/0/0"))
Для ed25519 все ноды должны быть "hardened", с опострофом. Во всех 3ех конфигах

2024-09-23 15:21 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/common/derivation/DerivationConfigV3.kt
> +            -> mapOf(AddressType.Default to DerivationPath("m/44'/246'/0'/0/0"))
Исправил

2024-09-23 15:54 UTC, dbaturin approved these changes

2024-09-23 18:45 UTC, Yoggam1 approved these changes

2024-09-24 08:00 UTC, kozarezvlad approved these changes

2024-09-24 08:00 UTC, merged