AND-8713 Fixed Tron and Solana transaction sending
tangem/blockchain-sdk-kotlin-old pull request #800
Opened 2024-10-08 15:19 UTC by Sateetas

2024-10-08 16:29 UTC, nzeeei submitted a review, later dismissed

2024-10-09 12:38 UTC, dbaturin requested changes
Мы делаем специальный случай на случай, если в sendMultiple придёт несколько транзакций и отправляем при этом опять же в sendMultiple родительского класса? Это сейчас там специфичная заглушка на 1 транзакцию, а в будущем может что-то другое быть. Почему бы сразу на одиночный сенд это не перенаправить?

2024-10-10 10:39 UTC, Sateetas commented
> Мы делаем специальный случай на случай, если в sendMultiple придёт несколько транзакций и отправляем при этом опять же в sendMultiple родительского класса? Это сейчас там специфичная заглушка на 1 транзакцию, а в будущем может что-то другое быть. Почему бы сразу на одиночный сенд это не перенаправить?

да, идейно так будет правильнее
вдобавок подрефачил TransactionSender, убрал из него реализацию отправки нескольких транзакций по умолчанию

2024-10-11 08:04 UTC, nzeeei approved these changes

2024-10-11 09:42 UTC, dbaturin approved these changes

2024-10-11 09:53 UTC, Mama1emon approved these changes

2024-10-11 09:53 UTC, merged