AND-8609: Add CasperAddressService
tangem/blockchain-sdk-kotlin-old pull request #804
Opened 2024-10-11 03:20 UTC by nzeeei

2024-10-11 04:40 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/casper/CasperAddressService.kt
> +class CasperAddressService : AddressService() {
internal

2024-10-11 04:40 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/casper/CasperConstants.kt
> +object CasperConstants {
internal

2024-10-11 08:03 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/casper/CasperConstants.kt
> +object CasperConstants {
Done

2024-10-11 08:03 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/casper/CasperAddressService.kt
> +class CasperAddressService : AddressService() {
Done

2024-10-11 09:54 UTC, Mama1emon approved these changes, later dismissed

2024-10-11 14:08 UTC, ndbaturin requested changes

2024-10-11 14:08 UTC, ndbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/casper/CasperAddressService.kt
> +        return addressChecksum == addressChecksum.hexToBytes().checksum()
Что-то тут странное

2024-10-11 14:08 UTC, ndbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/casper/cashaddr/CasperCashAddr.kt
> +object CasperCashAddr {
Это имеет какое-то отношение к формату CashAddr? Вроде совсем не похоже, по ссылке ничего не вижу, не гуглится сходу

2024-10-11 14:08 UTC, ndbaturin commented on blockchain/src/main/java/com/tangem/blockchain/extensions/ByteArray.kt
> +fun ByteArray.toHex(): String = joinToString(separator = "") { eachByte -> "%02x".format(eachByte) }
У нас уже есть экстеншн toHexString

2024-10-11 15:59 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/casper/CasperAddressService.kt
> +        return addressChecksum == addressChecksum.hexToBytes().checksum()
Done

2024-10-11 15:59 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/casper/cashaddr/CasperCashAddr.kt
> +object CasperCashAddr {
Изменил название

2024-10-11 15:59 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/extensions/ByteArray.kt
> +fun ByteArray.toHex(): String = joinToString(separator = "") { eachByte -> "%02x".format(eachByte) }
unused, убрал

2024-10-11 16:33 UTC, ndbaturin approved these changes
Ещё бы тест кейс для sameCase адресов добавить не помешало

2024-10-14 09:34 UTC, Yoggam1 approved these changes

2024-10-14 13:39 UTC, dbaturin approved these changes

2024-10-15 08:12 UTC, Mama1emon approved these changes

2024-10-15 08:12 UTC, merged