AND-8743 & AND-8736
tangem/blockchain-sdk-kotlin-old pull request #805
Opened 2024-10-11 11:02 UTC by iMaks99

2024-10-11 11:11 UTC, Mama1emon approved these changes

2024-10-11 12:44 UTC, Yoggam1 approved these changes

2024-10-11 14:59 UTC, ndbaturin requested changes

2024-10-11 14:59 UTC, ndbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +                    .setGasPrice(ByteString.copyFrom(feePrice.toByteArray()))
Если это фикс для конкретной валюты, то зачем менять это для всех? Может сломать что-то. Например, в каком-нибудь оптимизме будет в фи включён L2 fee и получится завышенный газ прайс, так ещё и падать будет при попытке все средства отправить. Мы уже так считали в билдере раньше, это уже приводило к проблемам.

2024-10-11 14:59 UTC, ndbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> -                .setAmount(ByteString.copyFrom(contract.value))
Транзакция к контракту вполне может иметь ещё и value в нативной валюте, который отправляется вместе с ней. Убирать не вариант.

Просто тут смешали что-то вcё в одну кучу. Это и амаунт в токене может быть и в нативной валюте. Почему данные о value лежат в DestinationType, это вообще за гранью моего понимания, надо было внимательнее ревьюить до этого.

Надо как-то по-человечески отрефакторить это

2024-10-11 17:08 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +                    .setGasPrice(ByteString.copyFrom(feePrice.toByteArray()))
Это фикс не связан с валютой, но был обнаружен в рамках теста валюты и все

2024-10-11 17:13 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> -                .setAmount(ByteString.copyFrom(contract.value))
Так как сейчас у нас нет таких кейсов, создам задачу на добавление этого кейса (https://tangem.atlassian.net/browse/AND-8751). Иначе без фикса не будет работать аппрув и возможно что-то еще

2024-10-11 17:14 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +                    .setGasPrice(ByteString.copyFrom(feePrice.toByteArray()))
Эта логика есть в LegacyBuilder, пропустили при миграции на Trust

2024-10-14 11:27 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> -                .setAmount(ByteString.copyFrom(contract.value))
Как нет? А WalletConnect?

2024-10-14 11:34 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +                    .setGasPrice(ByteString.copyFrom(feePrice.toByteArray()))
Если плохая логика есть в легаси билдере, это не значит, что её надо тащить в новый. Надо фиксить в другом месте, где проблема с выставлением параметра gasPrice, или почему вообще мы от него тут отказываемся?

2024-10-18 06:35 UTC, closed without merging