AND-8751 Add ability to add coin amount along with token amount in Ethereum
tangem/blockchain-sdk-kotlin-old pull request #808
Opened 2024-10-16 14:50 UTC by Mama1emon

2024-10-16 15:10 UTC, MasterBin requested changes

2024-10-16 15:10 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +                .apply {
В данном случае будет работать, но для билдеров не всегда характерно изменять внутреннее состояние. Обычно создается новый инстанс с примененным параметром. Поэтому лучше какой-нибудь let или run заюзать

2024-10-16 15:10 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +                val gasPrice = fee.gasPrice.takeUnless(BigInteger::isZero) ?: calculateGasPrise()
```suggestion
                val gasPrice = fee.gasPrice.takeUnless(BigInteger::isZero) ?: run {
                    val feeValue = fee.amount.value
                        ?.movePointRight(fee.amount.decimals)
                        ?.toBigInteger()
                        ?: error("Transaction fee must be specified")

                    feeValue.divide(fee.gasLimit)
                }
```

2024-10-16 15:10 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +                val gasPrice = fee.gasPrice.takeUnless(BigInteger::isZero) ?: calculateGasPrise()
nit

2024-10-17 05:48 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +                .apply {
Это реально RC? 😆

2024-10-17 07:51 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +                .apply {
Исправил

2024-10-17 07:51 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +                val gasPrice = fee.gasPrice.takeUnless(BigInteger::isZero) ?: calculateGasPrise()
Исправил

2024-10-17 09:07 UTC, Sateetas commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +                .apply {
ага, например в лямбдах, которые возвращают последний экспрешн
конструкция вида `x.apply { property = y }` будет возвращать x, без измененного property

2024-10-17 09:07 UTC, Sateetas approved these changes

2024-10-17 09:16 UTC, MasterBin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +                .apply {
реально RC, я считаю это критичным, особенно в бсдк

2024-10-17 09:16 UTC, MasterBin approved these changes

2024-10-17 11:29 UTC, dbaturin approved these changes

2024-10-17 11:29 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +import org.ton.bigint.isZero
Как он сюда пробрался при наличии встроенного Котлиновского?)

2024-10-17 11:31 UTC, Mama1emon commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/ethereum/txbuilder/EthereumTWTransactionBuilder.kt
> +import org.ton.bigint.isZero
Поправлю

2024-10-17 11:41 UTC, merged