AND-9157 Fact0rn support
tangem/blockchain-sdk-kotlin-old pull request #844
Opened 2024-11-25 06:48 UTC by nemelianov-tangem

- [x] https://github.com/tangem/tangem-app-config/pull/118

2024-11-25 08:09 UTC, MasterBin submitted a review, later dismissed

2024-11-25 11:53 UTC, kozarezvlad approved these changes, later dismissed

2024-11-28 13:47 UTC, kozarezvlad commented
Пустые классы можем без Дениса в целом влить

2024-11-28 13:57 UTC, Mama1emon submitted a review, later dismissed

2024-12-09 12:08 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/factorn/network/Fact0rnNetworkService.kt
> +internal class Fact0rnNetworkService(
Это тот который не юзается теперь? Мб пометить как то докой

2024-12-10 07:23 UTC, kozarezvlad submitted a review, later dismissed

2024-12-11 09:42 UTC, nzeeei approved these changes, later dismissed

2024-12-11 12:28 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/factorn/network/Fact0rnNetworkService.kt
> +        private val PRIORITY_FEE_MULTIPLIER = 5.toBigDecimal()
Откуда эти значения взялись? В Radiant используется Electrum, блоки так же часто, так почему здесь другие? Особенно основное - MINIMAL_NUMBER_OF_CONFIRMATION_BLOCKS

2024-12-11 12:49 UTC, nemelianov-tangem commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/factorn/network/Fact0rnNetworkService.kt
> +        private val PRIORITY_FEE_MULTIPLIER = 5.toBigDecimal()
в [исходниках константы кол-ва блоков](https://github.com/FACT0RN/FactWallet/blob/master/electrum/simple_config.py#L24) И как используют [раз](https://github.com/FACT0RN/FactWallet/blob/master/electrum/interface.py#L730) и [два](https://github.com/FACT0RN/FactWallet/blob/master/electrum/network.py#L524) Я взял 25 10 5 для minimal normal priority соотвественно

2024-12-11 17:11 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/factorn/network/Fact0rnNetworkService.kt
> +        private val PRIORITY_FEE_MULTIPLIER = 5.toBigDecimal()
Не, это плохие цели по блокам. 25 блоков - это 4.5 часа. По биткоину (а время блока то же там) в провайдере, который использует количество блоков, мы запрашиваем с таким целевым количеством:

const val MINIMAL_FEE_BLOCK_AMOUNT = 8
const val NORMAL_FEE_BLOCK_AMOUNT = 4
const val PRIORITY_FEE_BLOCK_AMOUNT = 1

Умножение при этом не даёт предсказуемого эффекта. По хорошему, надо делать 3 запроса с разным целевым параметром этим. Если с этим какие-то проблемы (апишка тупит мб), то можно попробовать с параметрами как в Radiant домножать. Но лучше всё же 3 запроса

2024-12-11 17:12 UTC, dbaturin requested changes
Проблема для исправления в отдельном комменте выше

2024-12-12 06:13 UTC, nemelianov-tangem commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/factorn/network/Fact0rnNetworkService.kt
> +        private val PRIORITY_FEE_MULTIPLIER = 5.toBigDecimal()
поправил кол-во блоков и добавил три запроса, при ошибке сделал через умножение

2024-12-13 07:29 UTC, kozarezvlad submitted a review, later dismissed

2024-12-16 10:30 UTC, dbaturin approved these changes

2024-12-16 14:54 UTC, kozarezvlad approved these changes

2024-12-16 15:06 UTC, Mama1emon approved these changes

2024-12-18 07:34 UTC, merged