AND-9119 [Staking] Implemented staking Polkadot. BSDK part
tangem/blockchain-sdk-kotlin-old pull request #848
Opened 2024-11-28 14:42 UTC by iMaks99

2024-11-28 15:21 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/polkadot/network/PolkadotCombinedProvider.kt
> +        Result.Success(balance)
Возникла мысль добавить extension

`fun BigDecimal?.orZero() = this ?: BigDecimal.ZERO`

2024-11-28 15:26 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/polkadot/models/PolkadotCompiledTransaction.kt
> +import shadow.com.google.gson.annotations.SerializedName
SerializedName из gson лучше сразу убрать, и если модель не участвует в навигации, то заменить на moshi

2024-11-28 16:25 UTC, Mama1emon approved these changes, later dismissed

2024-11-29 11:23 UTC, nzeeei submitted a review, later dismissed

2024-12-09 18:06 UTC, dbaturin requested changes

2024-12-09 18:06 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/polkadot/PolkadotTransactionBuilder.kt
> +    private fun encodeCheckMetadataHashMode(codecWriter: ScaleCodecWriter, specVersion: Int) {
Почти дубль уже имеющегося метода. Может использование предыдущего к новому привести, вроде не проблема совсем?

2024-12-09 18:06 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/polkadot/PolkadotTransactionBuilder.kt
> +    private fun encodeCheckMetadataHash(codecWriter: ScaleCodecWriter, specVersion: Int) {
То же самое, почти точный дубль

2024-12-09 18:06 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/polkadot/PolkadotTransactionBuilder.kt
> +        const val TRANSACTION_LIFE_PERIOD = 128L
Дубль константы из wallet manager.

2024-12-09 18:06 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/polkadot/PolkadotTransactionBuilder.kt
> +    private fun encodeEraNonceTip(codecWriter: ScaleCodecWriter, compiledTx: PolkadotCompiledTransaction.Inner) {
Почти дубль, но тут проставляем "life period" здесь. Лучше бы в одном месте.

2024-12-09 18:06 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/extensions/String.kt
> +private const val HEX_PREFIX = "0x"
Уже есть такая common константа.

2024-12-09 18:06 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/extensions/String.kt
> +private const val RADIX_FORMAT = 16
HEX_RADIX тогда уж, что бы обозначить, какой конкретно

2024-12-09 18:06 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/extensions/String.kt
> +fun String.hexToInt(default: Int = 0): Int {
Такая функция есть встроенная в Kotlin.

2024-12-10 09:08 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/polkadot/PolkadotTransactionBuilder.kt
> +    private fun encodeEraNonceTip(codecWriter: ScaleCodecWriter, compiledTx: PolkadotCompiledTransaction.Inner) {
Здесь можно выделить создаение эры из block number, а вот входные данные для compiled и uncompiled разные. Здесь думаю не критично

2024-12-10 09:14 UTC, iMaks99 commented on blockchain/src/main/java/com/tangem/blockchain/extensions/String.kt
> +fun String.hexToInt(default: Int = 0): Int {
Есть, но там она не nullable и нельзя указать дефолтное значение. Сделал версию, по аналогии с другими методами там же

2024-12-11 20:55 UTC, dbaturin approved these changes, later dismissed

2024-12-12 06:03 UTC, iiiburnyiii submitted a review, later dismissed

2024-12-12 06:03 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/polkadot/extensions/ExtrinsicUtils.kt
> +fun makeEraFromBlockNumber(blockNumber: Long): Era {
Это должно смотреть наружу из SDK? Если нет, то сделай internal, пожалуйста.

2024-12-12 06:03 UTC, iiiburnyiii commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/polkadot/models/PolkadotCompiledTransaction.kt
> +data class PolkadotCompiledTransaction(
internal?

2024-12-13 09:29 UTC, iiiburnyiii approved these changes

2024-12-25 10:36 UTC, kozarezvlad approved these changes

2025-01-09 13:43 UTC, dbaturin approved these changes

2025-01-09 13:44 UTC, merged