AND-8877 Add KRC20 base support
tangem/blockchain-sdk-kotlin-old pull request #850
Opened 2024-11-29 09:17 UTC by nzeeei

2024-12-02 16:32 UTC, dbaturin requested changes

2024-12-02 16:32 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/KaspaTransactionBuilder.kt
> +    fun buildToSend(signatures: ByteArray, transaction: KaspaTransaction = this.transaction): KaspaTransactionBody {
Не нравится, что есть дефолт тут, на баг напрашиваемся. Давайте может совсем уберём стейт из билдера вместе с дефолтом?

2024-12-02 16:32 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/KaspaWalletManager.kt
> +            }
Если один из результатов успешно приходит, не хотим ли мы его использовать?
Что если апишка для KRC20 отвалится, мы баланс обычной Каспы баланс не будем показывать тем, у кого токен добавлен.

Я знаю, что мы так нигде не делаем, но мы везде одну и ту же апишку дёргаем, а тут другую, так ещё и без резерва. Надо бы проработать это, мне кажется, и в iOS тоже.

2024-12-02 16:32 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/KaspaWalletManager.kt
> +    private suspend fun store(token: Token, data: BlockchainSavedData.KaspaKRC20IncompleteTokenTransaction) {
Может `storeIncompleteTokenTransaction`, по аналогии с функцией ниже? Что бы не путать с более базовым методом, как минимум

2024-12-03 06:57 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/krc20/model/CommitTransaction.kt
> +data class CommitTransaction(
internal

2024-12-03 06:57 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/krc20/model/Envelope.kt
> +data class Envelope(
internal

2024-12-03 06:57 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/krc20/KaspaKRC20RestApiNetworkProvider.kt
> +                            throw exception.toBlockchainSdkError()
Если не смогли получить только для одного токена баланс, то завалим все остальные тоже?

2024-12-03 06:57 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/krc20/model/IncompleteTokenTransactionParams.kt
> +data class IncompleteTokenTransactionParams(
internal

2024-12-03 06:57 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/krc20/model/RedeemScript.kt
> +data class RedeemScript(
internal

2024-12-03 06:57 UTC, Yoggam1 commented on blockchain/src/main/java/com/tangem/blockchain/common/trustlines/AssetRequirementsManager.kt
> +    suspend fun discardRequirements(currencyType: CryptoCurrencyType) { }
1. Хорошо бы убрать дефолтную реализацию. Пускай каждый блокчейн сам решает и явно прописывает логику.
2. И Надо возвращать хоть какой-то рузельтат наружу. Например `SimpleResult`

2024-12-06 07:30 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/KaspaTransactionBuilder.kt
> +    fun buildToSend(signatures: ByteArray, transaction: KaspaTransaction = this.transaction): KaspaTransactionBody {
Done

2024-12-06 07:30 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/KaspaWalletManager.kt
> +            }
Done

2024-12-06 07:30 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/KaspaWalletManager.kt
> +    private suspend fun store(token: Token, data: BlockchainSavedData.KaspaKRC20IncompleteTokenTransaction) {
Done

2024-12-06 07:30 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/krc20/model/CommitTransaction.kt
> +data class CommitTransaction(
Done

2024-12-06 07:30 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/krc20/model/Envelope.kt
> +data class Envelope(
Done

2024-12-06 07:30 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/krc20/KaspaKRC20RestApiNetworkProvider.kt
> +                            throw exception.toBlockchainSdkError()
Fixed

2024-12-06 07:30 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/krc20/model/IncompleteTokenTransactionParams.kt
> +data class IncompleteTokenTransactionParams(
Done

2024-12-06 07:30 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/krc20/model/RedeemScript.kt
> +data class RedeemScript(
Done

2024-12-06 07:30 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/common/trustlines/AssetRequirementsManager.kt
> +    suspend fun discardRequirements(currencyType: CryptoCurrencyType) { }
Done

2024-12-06 14:15 UTC, dbaturin approved these changes

2024-12-06 15:16 UTC, kozarezvlad approved these changes

2024-12-06 15:16 UTC, merged