AND-9337, AND-9340, AND-9341, AND-9348, AND-9349, AND-9350, AND-9364: Fix KRC-20 issues
tangem/blockchain-sdk-kotlin-old pull request #855
Opened 2024-12-09 02:27 UTC by nzeeei

2024-12-09 10:21 UTC, kozarezvlad commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/KaspaTransactionBuilder.kt
> -        if (change < BigDecimal.ZERO) { // unspentsToSpend not enough to cover transaction amount
а куда уехала эта логика с max 84 utxo?

2024-12-09 18:50 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/KaspaTransactionBuilder.kt
> -        if (change < BigDecimal.ZERO) { // unspentsToSpend not enough to cover transaction amount
Проверка на utxo есть в `checkUtxoAmountLimit()`, логику этого метода обновил

2024-12-09 21:04 UTC, dbaturin requested changes

2024-12-09 21:04 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/common/UtxoAmountLimitProvider.kt
> +    fun checkUtxoAmountLimit(amount: BigDecimal, fee: BigDecimal, currencyType: CryptoCurrencyType): UtxoAmountLimit?
Эта функция для KRC20 токенов не имеет смысла.

CryptoCurrencyType - это вообще какая-то фигня, есть же AmountType, если нужно отдельный кейс только для токенов и коинов, то надо бы вложенный сделать, но никак не отдельный. Надо убрать это в принципе.

А есть какая-то причина для этого интерфейса вообще? Чем нас validateTransaction не устраивает?

2024-12-09 21:04 UTC, dbaturin commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/KaspaWalletManager.kt
> +                is Result.Failure -> Unit
successOr лаконичнее будет

2024-12-10 05:13 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/common/UtxoAmountLimitProvider.kt
> +    fun checkUtxoAmountLimit(amount: BigDecimal, fee: BigDecimal, currencyType: CryptoCurrencyType): UtxoAmountLimit?
Ревертнул, в приложении сделаю так, чтобы для токенов проверки не было

2024-12-10 05:13 UTC, nzeeei commented on blockchain/src/main/java/com/tangem/blockchain/blockchains/kaspa/KaspaWalletManager.kt
> +                is Result.Failure -> Unit
Заменил на map

2024-12-10 17:01 UTC, dbaturin approved these changes

2024-12-10 17:12 UTC, kozarezvlad approved these changes

2024-12-10 17:13 UTC, merged