AND-9347 Send (TON): cannot send some of ton's tokens if the amount is longer than Long (from support team)
tangem/blockchain-sdk-kotlin-old pull request #858
Opened 2024-12-16 10:13 UTC by Mama1emon

2024-12-16 15:19 UTC, dbaturin submitted a review, later dismissed

2024-12-18 06:37 UTC, nzeeei approved these changes, later dismissed

2024-12-24 10:57 UTC, iMaks99 approved these changes

2024-12-24 10:57 UTC, kozarezvlad requested changes
не льем с тэгом не из мастера

2025-01-09 17:30 UTC, closed without merging